# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""create the pom schema and its tables

Revision ID: a3f1c8d24b71
Revises:
Create Date: 2026-08-11 12:00:00.000000

Creates the ``pom`` schema and the run table inside it. The table was
``pom_discovery_run`` in the default schema; inside ``pom`` the prefix is stutter,
so it is simply ``discovery_run``.

Rewritten in place rather than extended by follow-up revisions, because none of this
has shipped -- there is no deployment whose data a move migration would preserve. The
cost is local: a machine that ran an earlier version of this revision has to drop
what it created and delete the ``a3f1c8d24b71`` row from ``alembic_version_sep`` by
hand, since the migration that would have moved it deliberately does not exist. Once
POM ships, this file freezes and changes become new revisions.

The schema is named symbolically throughout -- ``schema="pom_schema"``, translated by
the connection (``app/sep/migrations/env.py``) -- with the single exception of
``CREATE SCHEMA``, which is raw DDL and therefore untranslated. That statement asks
:func:`app.sep.pom.config.pom_schema` for the real name and does nothing when the
bind has no schemas.

Hand-written, and it has to stay that way: Alembic applies no ``schema_translate_map``
during autogenerate and ``include_schemas`` is off, so ``--autogenerate`` proposes
creating a literal ``pom_schema`` and re-creating these tables on every run. Treat an
autogenerated POM diff as a bug.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.sep.config import sep_settings
from app.sep.pom.config import POM_SCHEMA_SYMBOL, pom_schema


# revision identifiers, used by Alembic.
revision: str = "a3f1c8d24b71"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("pom_discovery",)
depends_on: Union[str, Sequence[str], None] = None


def _create_schema_if_needed() -> str | None:
    """Create POM's schema on a bind that has one, and report what it is called.

    :return: The real schema name, or ``None`` when the bind has no schemas and
        POM's tables therefore live in the default one.
    """
    schema = pom_schema(sep_settings.DATABASE)
    if schema is not None:
        op.execute(sa.schema.CreateSchema(schema, if_not_exists=True))
    return schema


def upgrade() -> None:
    schema = _create_schema_if_needed()

    # Inspect the schema the tables actually land in, asking for the *real* name --
    # the token is not a schema anything can be inspected in. Inspecting the default
    # schema would report "absent" against a database that already has them.
    existing = set(sa.inspect(op.get_bind()).get_table_names(schema=schema))

    if "discovery_run" not in existing:
        op.create_table(
            "discovery_run",
            sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
            # BaseUUIDSQLModel's own columns. Omitting them is the mistake that makes
            # the table exist and every query against it fail.
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column(
                "status",
                # The enum's member NAMES, not its values: SQLAlchemy's non-native
                # Enum persists by name, so a constraint listing the lowercase values
                # rejects every insert the model makes.
                sa.Enum(
                    "RUNNING",
                    "SUCCESS",
                    "PARTIAL",
                    "FAILED",
                    name="proberunstatus",
                    native_enum=False,
                    create_constraint=True,
                ),
                nullable=False,
            ),
            sa.Column("services_total", sa.Integer(), nullable=False),
            sa.Column("services_resolved", sa.Integer(), nullable=False),
            sa.Column("services_orphaned", sa.Integer(), nullable=False),
            sa.Column("services_answered", sa.Integer(), nullable=False),
            sa.Column(
                "facts",
                postgresql.JSONB(astext_type=sa.Text()).with_variant(
                    sa.JSON(), "sqlite"
                ),
                nullable=False,
                server_default="[]",
            ),
            sa.Column(
                "nodes",
                postgresql.JSONB(astext_type=sa.Text()).with_variant(
                    sa.JSON(), "sqlite"
                ),
                nullable=False,
                server_default="[]",
            ),
            sa.Column("error", sa.String(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            schema=POM_SCHEMA_SYMBOL,
        )
        op.create_index(
            op.f("ix_pom_discovery_run_started_at"),
            "discovery_run",
            ["started_at"],
            unique=False,
            schema=POM_SCHEMA_SYMBOL,
        )
        op.create_index(
            op.f("ix_pom_discovery_run_status"),
            "discovery_run",
            ["status"],
            unique=False,
            schema=POM_SCHEMA_SYMBOL,
        )


def downgrade() -> None:
    # The schema itself is deliberately left behind: it is shared by every POM app
    # (app/sep/pom/__init__.py), so dropping it here would take another app's tables
    # with it, and each app's migrations are an independent branch with no ordering
    # between them.
    op.drop_index(
        op.f("ix_pom_discovery_run_status"),
        table_name="discovery_run",
        schema=POM_SCHEMA_SYMBOL,
    )
    op.drop_index(
        op.f("ix_pom_discovery_run_started_at"),
        table_name="discovery_run",
        schema=POM_SCHEMA_SYMBOL,
    )
    op.drop_table("discovery_run", schema=POM_SCHEMA_SYMBOL)
