"""add_index_for_periodic_tasks

Revision ID: f6d4492af6e2
Revises: dde1296cb2ae
Create Date: 2024-11-06 11:09:22.758791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6d4492af6e2'
down_revision: Union[str, None] = 'dde1296cb2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_period_task', 'periodictask', ['period', 'task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_period_task', table_name='periodictask')
    # ### end Alembic commands ###
