"""Use Enum for task owner

Revision ID: d15d7ea76f80
Revises: 7920c0e4aa23
Create Date: 2024-11-16 15:08:35.523293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd15d7ea76f80'
down_revision: Union[str, None] = '7920c0e4aa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE task SET owner='ANY' WHERE owner is NULL")
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.Enum('ALTERS', 'ARCHIVER', 'ANY', name='taskownerenum', native_enum=False),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sa.Enum('ALTERS', 'ARCHIVER', 'ANY', name='taskownerenum', native_enum=False),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   nullable=True)
    op.execute("UPDATE task SET owner=NULL WHERE owner='ANY'")
    # ### end Alembic commands ###
