# Copyright 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Update TaskBackendEnum

Revision ID: 7920c0e4aa23
Revises: 04f50684d5d7
Create Date: 2024-10-24 15:28:58.578669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7920c0e4aa23'
down_revision: Union[str, None] = '04f50684d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('backend',
               existing_type=sa.Enum('NOMAD', name='taskbackendenum'),
               type_=sa.Enum('NOMAD', 'PROXY', name='taskbackendenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('backend',
               existing_type=sa.Enum('NOMAD', 'PROXY', name='taskbackendenum', native_enum=False),
               type_=sa.Enum('NOMAD', name='taskbackendenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
