"""Update TaskBackendEnum

Revision ID: 7920c0e4aa23
Revises: 04f50684d5d7
Create Date: 2024-10-24 15:28:58.578669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7920c0e4aa23'
down_revision: Union[str, None] = '04f50684d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('backend',
               existing_type=sa.Enum('NOMAD', name='taskbackendenum'),
               type_=sa.Enum('NOMAD', 'PROXY', name='taskbackendenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('backend',
               existing_type=sa.Enum('NOMAD', 'PROXY', name='taskbackendenum', native_enum=False),
               type_=sa.Enum('NOMAD', name='taskbackendenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
