"""create_periodictask_table

Revision ID: 8b33b35a7e69
Revises: 04f50684d5d7
Create Date: 2024-10-25 14:47:51.434868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b33b35a7e69'
down_revision: Union[str, None] = '04f50684d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodictask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execute_request', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_period', 'periodictask', ['period'], unique=False)
    op.create_index(op.f('ix_periodictask_task_id'), 'periodictask', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodictask_task_id'), table_name='periodictask')
    op.drop_index('ix_period', table_name='periodictask')
    op.drop_table('periodictask')
    # ### end Alembic commands ###
