"""Create Task and TaskHistory tables

Revision ID: 04f50684d5d7
Revises: 
Create Date: 2024-09-18 15:42:36.634240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04f50684d5d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('backend', sa.Enum('NOMAD', name='taskbackendenum'), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_deleted_at'), 'task', ['deleted_at'], unique=False)
    op.create_index('ix_task_deleted_at_name', 'task', ['deleted_at', 'name'], unique=False)
    op.create_index('ix_task_deleted_at_name_is_template', 'task', ['deleted_at', 'name', 'is_template'], unique=False)
    op.create_index('ix_task_deleted_at_owner', 'task', ['deleted_at', 'owner'], unique=False)
    op.create_index(op.f('ix_task_is_template'), 'task', ['is_template'], unique=False)
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=True)
    op.create_index(op.f('ix_task_owner'), 'task', ['owner'], unique=False)
    op.create_table('taskhistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_request', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', name='taskhistorystatusenum'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskhistory_status'), 'taskhistory', ['status'], unique=False)
    op.create_index(op.f('ix_taskhistory_task_id'), 'taskhistory', ['task_id'], unique=False)
    op.create_index('ix_taskhistory_task_id_status', 'taskhistory', ['task_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_taskhistory_task_id_status', table_name='taskhistory')
    op.drop_index(op.f('ix_taskhistory_task_id'), table_name='taskhistory')
    op.drop_index(op.f('ix_taskhistory_status'), table_name='taskhistory')
    op.drop_table('taskhistory')
    op.drop_index(op.f('ix_task_owner'), table_name='task')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_index(op.f('ix_task_is_template'), table_name='task')
    op.drop_index('ix_task_deleted_at_owner', table_name='task')
    op.drop_index('ix_task_deleted_at_name_is_template', table_name='task')
    op.drop_index('ix_task_deleted_at_name', table_name='task')
    op.drop_index(op.f('ix_task_deleted_at'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
