"""Add started_at and finished_at fields to TaskHistory

Revision ID: 80e592531cd7
Revises: 064c3cec8450
Create Date: 2025-05-03 14:54:29.448159

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80e592531cd7'
down_revision: Union[str, None] = '064c3cec8450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskhistory', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('taskhistory', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # ### data migration ###
    taskhistory_table = sa.Table(
        'taskhistory',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('execution_request', sa.JSON(), nullable=False),
        sa.Column('status', sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', name='taskhistorystatusenum'), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True)),
        sa.Column('finished_at', sa.DateTime(timezone=True)),
    )
    conn = op.get_bind()
    rows = conn.execute(
        sa.select(taskhistory_table.c.id, taskhistory_table.c.execution_request)
    ).fetchall()
    for id_, execution_request in rows:
        if execution_request and isinstance(execution_request, dict):
            tracking = execution_request.get('tracking', {})
            update_values = {
                'started_at': tracking.get('started_at'),
                'finished_at': tracking.get('finished_at'),
            }
            update_values = {k: datetime.fromisoformat(v) for k, v in update_values.items() if v}
            if update_values:
                conn.execute(
                    taskhistory_table.update().where(taskhistory_table.c.id == id_).values(**update_values)
                )
    # ### end data migration ###


def downgrade() -> None:
    # ### data migration ###
    taskhistory_table = sa.Table(
        'taskhistory',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('execution_request', sa.JSON(), nullable=False),
        sa.Column('status', sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', name='taskhistorystatusenum'), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True)),
        sa.Column('finished_at', sa.DateTime(timezone=True)),
    )
    conn = op.get_bind()
    rows = conn.execute(
        sa.select(
            taskhistory_table.c.id,
            taskhistory_table.c.execution_request,
            taskhistory_table.c.started_at,
            taskhistory_table.c.finished_at,
        )
    ).fetchall()
    for id_, execution_request, started_at, finished_at in rows:
        if execution_request and isinstance(execution_request, dict) and (started_at or finished_at):
            update_values = {
                'started_at': started_at,
                'finished_at': finished_at,
            }
            update_values = {k: v.isoformat() for k, v in update_values.items() if v and isinstance(v, datetime)}
            execution_request['tracking'] = execution_request.get('tracking', {})
            execution_request['tracking'].update(update_values)
            conn.execute(
                taskhistory_table.update().where(taskhistory_table.c.id == id_).values(
                    execution_request=execution_request
                )
            )
    # ### end data migration ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'finished_at')
    op.drop_column('taskhistory', 'started_at')
    # ### end Alembic commands ###
