"""add_user_tracking_fields

Revision ID: 4ac8c028542f
Revises: d39d37d3dcdc
Create Date: 2025-09-24 12:15:31.800709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ac8c028542f'
down_revision: Union[str, None] = 'd39d37d3dcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('task', sa.Column('last_updated_by', sa.Uuid(), nullable=True))
    op.add_column('taskhistory', sa.Column('executed_by', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'executed_by')
    op.drop_column('task', 'last_updated_by')
    op.drop_column('task', 'created_by')
    # ### end Alembic commands ###
