"""use_anonymize_for_masking

Revision ID: 7a307554c1cd
Revises: d15d7ea76f80
Create Date: 2025-03-03 03:33:14.684136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a307554c1cd'
down_revision: Union[str, None] = 'd15d7ea76f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('anonymize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'anonymize')
    # ### end Alembic commands ###
