"""add user tracking fields

Revision ID: c7b630b052ba
Revises: d39d37d3dcdc
Create Date: 2025-09-03 20:39:20.391164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7b630b052ba'
down_revision: Union[str, None] = 'd39d37d3dcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task', sa.Column('last_edit_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_task_created_by'), 'task', ['created_by'], unique=False)
    op.create_index(op.f('ix_task_last_edit_by'), 'task', ['last_edit_by'], unique=False)
    op.add_column('taskhistory', sa.Column('executed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_taskhistory_executed_by'), 'taskhistory', ['executed_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskhistory_executed_by'), table_name='taskhistory')
    op.drop_column('taskhistory', 'executed_by')
    op.drop_index(op.f('ix_task_last_edit_by'), table_name='task')
    op.drop_index(op.f('ix_task_created_by'), table_name='task')
    op.drop_column('task', 'last_edit_by')
    op.drop_column('task', 'created_by')
    # ### end Alembic commands ###
