"""Add output_files_path to Task

Revision ID: 4e346919fc0f
Revises: 3b15a15ac473
Create Date: 2025-09-25 04:48:36.303838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e346919fc0f'
down_revision: Union[str, None] = '3b15a15ac473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('output_files_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'output_files_path')
    # ### end Alembic commands ###
