"""Add alert_on_fail field to Task

Revision ID: b4f0b7b50441
Revises: 36f2b569e7bb
Create Date: 2025-06-11 10:21:03.875488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import false

# revision identifiers, used by Alembic.
revision: str = 'b4f0b7b50441'
down_revision: Union[str, None] = '36f2b569e7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('alert_on_fail', sa.Boolean(), nullable=False, server_default=false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'alert_on_fail')
    # ### end Alembic commands ###
