"""change_task_owner_to_varchar32

Revision ID: 306917ba8517
Revises: 19605d228fa3
Create Date: 2025-08-13 16:32:45.334416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '306917ba8517'
down_revision: Union[str, None] = '19605d228fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sa.VARCHAR(length=12),
                   type_=sa.VARCHAR(length=32),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sa.VARCHAR(length=32),
                   type_=sa.VARCHAR(length=12),
                   existing_nullable=False)
    # ### end Alembic commands ###
