"""Add anonymize_mask field to TaskHistory

Revision ID: 3b15a15ac473
Revises: d39d37d3dcdc
Create Date: 2025-09-16 17:45:54.871842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b15a15ac473'
down_revision: Union[str, None] = 'd39d37d3dcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('anonymize_mask',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    op.add_column('taskhistory', sa.Column('anonymize_mask', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'anonymize_mask')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('anonymize_mask',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
