"""Add anonymize field at task and taskhistory

Revision ID: ce550342d4b5
Revises: 36f2b569e7bb
Create Date: 2025-06-03 13:39:08.075328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce550342d4b5'
down_revision: Union[str, None] = '36f2b569e7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('anonymize', sa.Integer(), nullable=False))
    op.add_column('taskhistory', sa.Column('anonymized_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'anonymized_items')
    op.drop_column('task', 'anonymize')
    # ### end Alembic commands ###
