"""Update Task Owner enum

Revision ID: 064c3cec8450
Revises: d15d7ea76f80
Create Date: 2025-05-03 13:59:09.172312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '064c3cec8450'
down_revision: Union[str, None] = 'd15d7ea76f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sa.Enum('ALTERS', 'ARCHIVER', 'ANY', name='taskownerenum', native_enum=False),
                   type_=sa.Enum('ANY', 'ALTERS', 'ARCHIVER', 'BACKUPS', 'CHECKSUMS', 'BACKUP_MONGO', name='taskowner', native_enum=False),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sa.Enum('ANY', 'ALTERS', 'ARCHIVER', 'BACKUPS', 'CHECKSUMS', 'BACKUP_MONGO', name='taskowner', native_enum=False),
                   type_=sa.Enum('ALTERS', 'ARCHIVER', 'ANY', name='taskownerenum', native_enum=False),
                   nullable=False)
    # ### end Alembic commands ###
