"""Remove is_template field from Task

Revision ID: eb90965e9ac6
Revises: d15d7ea76f80
Create Date: 2025-04-08 12:54:43.313055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb90965e9ac6'
down_revision: Union[str, None] = 'd15d7ea76f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_deleted_at_name_is_template', table_name='task')
    op.drop_index('ix_task_is_template', table_name='task')
    op.drop_column('task', 'is_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_template', sa.BOOLEAN(), nullable=False))
    op.create_index('ix_task_is_template', 'task', ['is_template'], unique=False)
    op.create_index('ix_task_deleted_at_name_is_template', 'task', ['deleted_at', 'name', 'is_template'], unique=False)
    # ### end Alembic commands ###
