"""add field anonymize at task

Revision ID: 403e20d43086
Revises: b4f0b7b50441
Create Date: 2025-06-18 13:39:22.747808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '403e20d43086'
down_revision: Union[str, None] = 'b4f0b7b50441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('anonymize', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'anonymize')
    # ### end Alembic commands ###
