# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Add field sync_in_progress_started_at to TaskHistory

Revision ID: bec093f02c15
Revises: 80e592531cd7
Create Date: 2025-05-15 19:33:28.337600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bec093f02c15'
down_revision: Union[str, None] = '80e592531cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskhistory', sa.Column('sync_in_progress_started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_taskhistory_status_sync_in_progress_started_at', 'taskhistory', ['status', 'sync_in_progress_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_taskhistory_status_sync_in_progress_started_at', table_name='taskhistory')
    op.drop_column('taskhistory', 'sync_in_progress_started_at')
    # ### end Alembic commands ###
