# Copyright 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""add user tracking fields

Revision ID: 0b852d9798ef
Revises: 4e346919fc0f
Create Date: 2025-10-07 17:52:51.941311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b852d9798ef'
down_revision: Union[str, None] = '4e346919fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task', sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('taskhistory', sa.Column('executed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'executed_by')
    op.drop_column('task', 'last_updated_by')
    op.drop_column('task', 'created_by')
    # ### end Alembic commands ###
