# Copyright 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Update TaskHistory status enum

Revision ID: 68379e926e7c
Revises: bec093f02c15
Create Date: 2025-05-20 11:44:16.749511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68379e926e7c'
down_revision: Union[str, None] = 'bec093f02c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskhistory', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', name='taskhistorystatusenum'),
               type_=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', 'STOPPED', 'LOST', name='taskhistorystatusenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskhistory', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', 'STOPPED', 'LOST', name='taskhistorystatusenum', native_enum=False),
               type_=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', name='taskhistorystatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
