# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Add anonymize_mask field to TaskHistory

Revision ID: 3b15a15ac473
Revises: d39d37d3dcdc
Create Date: 2025-09-16 17:45:54.871842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b15a15ac473'
down_revision: Union[str, None] = 'd39d37d3dcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('anonymize_mask',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    op.add_column('taskhistory', sa.Column('anonymize_mask', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'anonymize_mask')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('anonymize_mask',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
