"""add user tracking fields

Revision ID: 0b852d9798ef
Revises: 4e346919fc0f
Create Date: 2025-10-07 17:52:51.941311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b852d9798ef'
down_revision: Union[str, None] = '4e346919fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task', sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('taskhistory', sa.Column('executed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'executed_by')
    op.drop_column('task', 'last_updated_by')
    op.drop_column('task', 'created_by')
    # ### end Alembic commands ###
