"""Add anonymize field at Task

Revision ID: 40cfa8c5f67d
Revises: 36f2b569e7bb
Create Date: 2025-06-03 22:16:08.898958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40cfa8c5f67d'
down_revision: Union[str, None] = '36f2b569e7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('anonymize', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'anonymize')
    # ### end Alembic commands ###
