"""Update TaskHistory status enum

Revision ID: 68379e926e7c
Revises: bec093f02c15
Create Date: 2025-05-20 11:44:16.749511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68379e926e7c'
down_revision: Union[str, None] = 'bec093f02c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskhistory', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', name='taskhistorystatusenum'),
               type_=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', 'STOPPED', 'LOST', name='taskhistorystatusenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskhistory', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', 'STOPPED', 'LOST', name='taskhistorystatusenum', native_enum=False),
               type_=sa.Enum('FAILED', 'PENDING', 'RUNNING', 'SUCCESS', name='taskhistorystatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
