# Copyright 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Update Task Owner enum

Revision ID: 064c3cec8450
Revises: d15d7ea76f80
Create Date: 2025-05-03 13:59:09.172312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '064c3cec8450'
down_revision: Union[str, None] = 'd15d7ea76f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sa.Enum('ALTERS', 'ARCHIVER', 'ANY', name='taskownerenum', native_enum=False),
                   type_=sa.Enum('ANY', 'ALTERS', 'ARCHIVER', 'BACKUPS', 'CHECKSUMS', 'BACKUP_MONGO', name='taskowner', native_enum=False),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('owner',
                   existing_type=sa.Enum('ANY', 'ALTERS', 'ARCHIVER', 'BACKUPS', 'CHECKSUMS', 'BACKUP_MONGO', name='taskowner', native_enum=False),
                   type_=sa.Enum('ALTERS', 'ARCHIVER', 'ANY', name='taskownerenum', native_enum=False),
                   nullable=False)
    # ### end Alembic commands ###
