"""use_anonymized_entities_for_decryption

Revision ID: 9f88b9aa2c57
Revises: 4fb0425ef003
Create Date: 2025-03-05 21:48:13.179627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f88b9aa2c57'
down_revision: Union[str, None] = '4fb0425ef003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskhistory', sa.Column('anonymized_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskhistory', 'anonymized_items')
    # ### end Alembic commands ###
