python:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - '**/**.py'
      - 'pyproject.toml'
      - 'poetry.lock'

frontend:
- any:
  - changed-files:
    - any-glob-to-any-file:
      - 'frontend/**'
      - 'package.json'

skip-test:
- all:
  - changed-files:
    - any-glob-to-all-files:
      - 'CODEOWNERS'
      - 'README.md'
      - '.gitignore'
      - 'dist/**'
- head-branch:
  - '^dependabot/'
