python:
- any:
  - changed-files:
    - '**/**.py'
    - 'pyproject.toml'
    - 'poetry.lock'

skip-test:
- any-glob-to-all-files:
  - changed-files:
    - 'CODEOWNERS'
    - 'README.md'
    - '.gitignore'
    - 'dist/**'
