packages:
  - 'packages/*'
  - 'packages/plugins/*'
onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - '@percona/percona-ui'
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
allowBuilds:
  esbuild: true
  msw: true
