packages:
  - 'packages/*'
  - 'packages/plugins/*'
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - '@napi-rs/wasm-runtime'
allowBuilds:
  esbuild: true
  msw: true
overrides:
  brace-expansion@5.0.5: 5.0.6
  js-yaml@4.1.1: 4.2.0
