---
- hosts: all
  tasks:
  - name: Disable `ufw` firewall
    ansible.builtin.service:
      name: ufw
      enabled: false
      state: stopped
    become: true

  - name: Install `percona-release`
    ansible.builtin.apt:
      deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"
    become: true

  - name: Enable Percona Distribution for PostgreSQL repo
    ansible.builtin.command: 'percona-release setup -y ppg17'
    become: true
    changed_when: false

  - name: Install Percona Distribution for PostgreSQL server
    ansible.builtin.apt:
      name: percona-postgresql-17
      state: present
      update_cache: true
    become: true

  - name: Ensure PostgreSQL server service is enabled and started
    ansible.builtin.service:
      name: postgresql
      enabled: true
      state: started

  - name: Configure `postgresql.conf` for `listen_addresses`
    ansible.builtin.lineinfile:
      path: "/etc/postgresql/17/main/postgresql.conf"
      regexp: "^#?listen_addresses ="
      line: "listen_addresses = '*'"
    become: true
    notify: Restart PostgreSQL

  - name: Configure `pg_hba.conf` to allow remote connections
    ansible.builtin.lineinfile:
      path: "/etc/postgresql/17/main/pg_hba.conf"
      line: "host    all             all             0.0.0.0/0               scram-sha-256"
      insertafter: "# IPv4 local connections:"
    become: true
    notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
      become: true
...
