###########
# BUILDER #
###########

# Use an official Python runtime as a parent image
FROM docker.io/library/python:3.11-alpine AS builder

# Set work directory
WORKDIR /usr/src/sep

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FASTAPI_ENV production_docker

# Install system dependencies
RUN apk update && apk add --no-cache build-base libpq libpq-dev python3-dev

# Export requirements
RUN pip install --no-cache-dir wheel poetry==1.8.3 poetry-plugin-export
COPY ./pyproject.toml ./poetry.lock /usr/src/sep/
RUN poetry export --with postgresql --with redis -f requirements.txt --output requirements.txt

# Build Wheel archives for requirements
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/sep/wheels -r requirements.txt


