###########
# BUILDER #
###########

# Use an official Python runtime as a parent image
FROM docker.io/library/python:3.11-alpine AS builder

# Set work directory
WORKDIR /usr/src/sep

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FASTAPI_ENV production_docker

# Install dependencies
RUN apk update && apk add --no-cache g++

# Export requirements
RUN pip install --no-cache-dir wheel poetry==2.1.2 poetry-plugin-export
COPY ./pyproject.toml ./poetry.lock /usr/src/sep/
RUN poetry export --with postgresql --with syncpostgresql --with redis -f requirements.txt --output requirements.txt

# Build Wheel archives for requirements
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/sep/wheels -r requirements.txt
