x-api-environment:
  environment: &api-environment
    FASTAPI_ENV: production_docker
    LOGGING: debug

x-api-db-environment:
  environment: &api-db-environment
    <<: *api-environment
    DATABASE__ENGINE: postgresql
    DATABASE__USER: postgres
    DATABASE__PASSWORD: postgres
    DATABASE__HOST: sep-db
    DATABASE__PORT: 5432
    DATABASE__NAME: sep

services:
  casdoor:
    image: docker.io/casbin/casdoor-all-in-one
    volumes:
      - casdoor-data:/var/lib/mysql:z,rw
      - ./data/casdoor_init_data.json:/init_data.json
    expose:
      - 8000

  sep-db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_DB: sep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - sep-data:/var/lib/postgresql/data
    expose:
      - 5432

  inventory_api:
    image: sep-image:latest
    user: 1001:1001
    command: inventory
    expose:
      - 9001
    depends_on:
      - casdoor
    environment:
      <<: *api-db-environment
      UVICORN_HOST: inventory_api
      UVICORN_PORT: 9001
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-host-gateway}"

  tasks_api:
    image: sep-image:latest
    user: 1001:1001
    command: tasks
    expose:
      - 9002
    depends_on:
      - casdoor
      - sep-db
    environment:
      <<: *api-db-environment
      UVICORN_HOST: tasks_api
      UVICORN_PORT: 9002
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-host-gateway}"

  sep:
    image: sep-image:latest
    build: .
    user: 1001:1001
    command: sep
    expose:
      - 9000
    volumes:
      - ./static:/home/sep/app/static
    depends_on:
      - inventory_api
      - tasks_api
      - casdoor
    environment:
      <<: *api-db-environment
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 9000
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-host-gateway}"

  nginx:
    image: docker.io/library/nginx:1.27-alpine
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
      - "${CASDOOR_PORT:-9999}:9999"
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certs/sep/localhost-cert.pem:/etc/nginx/ssl/localhost-cert.pem
      - ./data/certs/sep/localhost-cert-key.pem:/etc/nginx/ssl/localhost-cert-key.pem
    depends_on:
      - sep

volumes:
  casdoor-data:
  sep-data:
