x-api-environment:
  environment: &api-environment
    FASTAPI_ENV: production_docker
    LOGGING: debug
    ENV_FILE: .env.docker

x-api-db-environment:
  environment: &api-db-environment
    <<: *api-environment
    DATABASE__ENGINE: postgresql
    DATABASE__USER: postgres
    DATABASE__PASSWORD: postgres
    DATABASE__HOST: sep-db
    DATABASE__PORT: 5432
    DATABASE__NAME: sep
    CELERY__BROKER_URL: redis://:${SEP_REDIS_PASSWORD}@redis:6379/0
    CELERY__BEAT_DBURI: postgresql://postgres:postgres@sep-db:5432
    CELERY__BEAT_SCHEMA: sep

services:
  casdoor:
    image: docker.io/casbin/casdoor-all-in-one
    volumes:
      - casdoor-data:/var/lib/mysql:z,rw
      - ./data/casdoor_init_data.json:/init_data.json
    expose:
      - 8000

  sep-db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_DB: sep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - sep-data:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: docker.io/library/redis:7-alpine
    command: redis-server --port 6379 --bind 127.0.0.1 --requirepass "${SEP_REDIS_PASSWORD}"
    environment:
      SEP_REDIS_PASSWORD: "${SEP_REDIS_PASSWORD}"
    expose:
      - 6379

  celery_worker:
    image: sep-image:latest
    user: 1001:1001
    entrypoint: /home/sep/app/entrypoint_celery.sh
    command: worker --loglevel=info
    depends_on:
      - sep-db
      - redis
      - casdoor
    environment:
      <<: *api-db-environment
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-host-gateway}"

  celery_beat:
    image: sep-image:latest
    user: 1001:1001
    entrypoint: /home/sep/app/entrypoint_celery.sh
    command: beat --scheduler=sqlalchemy --loglevel=info
    depends_on:
      - sep-db
      - redis
      - casdoor
      - celery_worker
    environment:
      <<: *api-db-environment

  inventory_api:
    image: sep-image:latest
    user: 1001:1001
    command: inventory
    expose:
      - 9001
    depends_on:
      - casdoor
      - sep-db
    environment:
      <<: *api-db-environment
      UVICORN_HOST: inventory_api
      UVICORN_PORT: 9001
      ALLOWED_HOSTS: '["inventory_api"]'
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-host-gateway}"

  tasks_api:
    image: sep-image:latest
    user: 1001:1001
    command: tasks
    expose:
      - 9002
    depends_on:
      - casdoor
      - sep-db
      - redis
      - celery_beat
    environment:
      <<: *api-db-environment
      UVICORN_HOST: tasks_api
      UVICORN_PORT: 9002
      ALLOWED_HOSTS: '["tasks_api"]'
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-host-gateway}"

  sep:
    image: sep-image:latest
    build: .
    user: 1001:1001
    command: sep
    expose:
      - 9000
    volumes:
      - ./static:/home/sep/app/static
    depends_on:
      - inventory_api
      - tasks_api
      - casdoor
      - sep-db
    environment:
      <<: *api-db-environment
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 9000
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-host-gateway}"

  nginx:
    image: docker.io/library/nginx:1.27-alpine
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
      - "${CASDOOR_PORT:-9999}:9999"
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certs/sep/localhost-cert.pem:/etc/nginx/ssl/localhost-cert.pem
      - ./data/certs/sep/localhost-cert-key.pem:/etc/nginx/ssl/localhost-cert-key.pem
    depends_on:
      - sep

volumes:
  casdoor-data:
  sep-data:
  celery-beat-data:
