[tool.poetry]
name = "sep"
version = "0.4.0-beta"
description = "SEP: Services Enablement Platform"
authors = [
    "Ceri Williams <ceri.williams@percona.com>",
    "Max Bubenick <max.bubenick@percona.com>",
    "Peter Addo <peter.addo@percona.com>",
    "Yan Orestes <yan.orestes@percona.com>",
]
maintainers = [
    "Ceri Williams <ceri.williams@percona.com>",
    "Max Bubenick <max.bubenick@percona.com>",
    "Peter Addo <peter.addo@percona.com>",
    "Yan Orestes <yan.orestes@percona.com>",
]
readme = "README.md"
repository = "https://github.com/percona/SEP"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: FastAPI",
    "Framework :: MkDocs",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Database",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Systems Administration",
    "Typing :: Typed"
]
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
aiohttp = "^3.11.10"
aioresponses = "^0.7.7"
idna = "^3.7"
itsdangerous = "^2.1.2"
pydantic = ">=2.4.0,<2.10.0"
PyYAML = "^6.0.1"
python-multipart = "^0.0.19"
python-nomad = "^2.0.0"
SQLAlchemy = "^2.0.34"
urllib3 = "^2.2.2"
uvicorn = {extras = ["standard"], version = "^0.32.0"}
cryptography = "^44.0.1"
pyjwt = "^2.10.1"
yarl = "^1.9.2"
jinja2 = "^3.1.5"
pydantic-settings = "^2.4.0"
email-validator = "^2.2.0"
greenlet = "^3.0.3"
aiosqlite = "^0.20.0"
alembic = "^1.13.2"
sqlmodel = "^0.0.22"
async-lru = "^2.0.4"
python-minifier = "^2.11.2"
starlette = "^0.41.3"
celery = "^5.4.0"
asgiref = "^3.8.1"
sqlalchemy-celery-beat = "0.8.0"
fastapi-csrf-protect = "^0.3.7"
fastapi = "^0.115.6"
httpx = "^0.28.0"
rich = "^13.9.4"
pygments = "^2.19.1"

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
pip-audit = "^2.7.3"
bandit = {extras = ["toml"], version = "^1.7.9"}
poetry-plugin-export = "^1.8.0"
ruff = "^0.9.4"
djlint = "^1.36.4"
jsbeautifier = "^1.15.1"
cssbeautifier = "^1.15.1"


[tool.poetry.group.mysql]
optional = true

[tool.poetry.group.mysql.dependencies]
aiomysql = "^0.2.0"

[tool.poetry.group.syncmysql]
optional = true

[tool.poetry.group.syncmysql.dependencies]
pymysql = "^1.1.1"

[tool.poetry.group.postgresql]
optional = true

[tool.poetry.group.postgresql.dependencies]
asyncpg = "^0.29.0"

[tool.poetry.group.syncpostgresql]
optional = true

[tool.poetry.group.syncpostgresql.dependencies]
psycopg2-binary = "^2.9.10"

[tool.poetry.group.redis]
optional = true

[tool.poetry.group.redis.dependencies]
redis = ">=4.5.2,<4.5.5 || >4.5.5,<6.0.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
pytest = "^8.3.3"
pytest-cov = "^6.0.0"
pytest-mock = "^3.14.0"
faker = "^30.8.2"
polyfactory = "^2.18.0"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
exclude_dirs = [
    ".git",
    ".github",
    "build",
    "venv",
    "app/tests/",
]

[tool.ruff]
fix = true
show-fixes = true
extend-exclude = [
    ".github",
    "build",
    "data",
    "docs",
    "etc",
    "app/*/migrations/*",
    "payload.py",
    "payload",
    "*_payload",
]
cache-dir = "build/tmp/.ruff_cache"
target-version = "py311"
force-exclude = true

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "D",
    "UP",
    "ANN0",
    "ANN2",
    "ASYNC",
    "S",
    "BLE001",
    "FBT",
    "B",
    "A",
    "COM818",
    "C4",
    "DTZ",
    "T100",
    "EXE",
    "ISC",
    "ICN001",
    "LOG",
    "G",
    "INP001",
    "PIE",
    "T20",
    "PT",
    "Q",
    "RSE102",
    "RET",
    "SLF001",
    "SIM",
    "TID252",
    "TC",
    "ARG",
    "PTH",
    "TD",
    "FIX",
    "ERA001",
    "PGH",
    "PL",
    "TRY",
    "FLY002",
    "PERF",
    "FURB",
    "RUF",
]
ignore = [
    "E501",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D213",
    "ISC001",
    "TC001",
    "FIX002",
    "TRY003",
    "RUF007",
    "RUF012", # Too much false positives with Pydantic subclasses (https://github.com/astral-sh/ruff/issues/5639)
    "PLR0913",
]
task-tags = ["TODO"]

[tool.ruff.lint.isort]
order-by-type = false

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
"sqlalchemy.Enum" = "EnumField"
"sqlmodel.Field" = "SQLField"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"config.py" = [
    "N802",
]
"app/core/config.py" = ["ARG003"]
"app/core/utils/fields.py" = ["TRY004"] # Pydantic validation code should raise ValueError
"app/tasks/celery.py" = ["ARG001"]
"test_*.py" = ["S", "ARG001", "ARG002", "ANN"]
"conftest.py" = ["S", "ARG001", "ARG002"]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
markers = [
    "syncmysql: require syncmysql dependencies",
]

[tool.coverage.run]
source = ["app"]
omit = [
    "__init__.py",
]

[tool.coverage.report]
show_missing = true
skip_empty = true

[tool.tox]
env_list = ["3.11", "3.12", "3.13"]

[tool.tox.env_run_base]
allowlist_externals = ["make"]
commands = [["make", "test"]]


[tool.djlint]
profile = "jinja"
ignore = "H021"
