default:
  AUTH_USER_MODEL: app.models.CasdoorUser
  CASDOOR:
    ENDPOINT: http://localhost:9999
    CERTIFICATE_PATH: data/token_jwt_key.pem
  OAUTH:
    REDIRECT_URI: http://localhost:8000/oauth/callback
    COOKIE_NAME: casdoorToken
  PMM:
    ENDPOINT: https://127.0.0.1:8443
    VERIFY_SSL: false
  TEMPLATES_DIR: templates
  BACKEND_CORS_ORIGINS:
    - http://localhost:8000
    - http://127.0.0.1:8000
  NOMAD:
    ENDPOINT: http://127.0.0.1:4646
  BASE_URI: http://localhost:8000
  PLUGINS:
    - NAME: Schema Change
      MODULE_NAME: alters
      URI_PATH: /alters
      CSS_CLASS: alters
development:
  INVENTORY_ENDPOINT: http://localhost:8000/api/inventory
  TASKS_ENDPOINT: http://localhost:8000/api/tasks
  PLUGINS:
    - NAME: Task Manager
      MODULE_NAME: tasks
      URI_PATH: /tasks
      CSS_CLASS: tasks
production_docker:
  SEP_ENDPOINT: http://0.0.0.0:8003
  INVENTORY_ENDPOINT: http://inventory_api:8001
  TASKS_ENDPOINT: http://tasks_api:8002
  PMM:
    ENDPOINT: https://host.docker.internal:8443
  CASDOOR:
    ENDPOINT: http://casdoor:8000
    FRONT_ENDPOINT: http://localhost:9999
    ALLOWED_ISSUERS:
      - http://localhost:9999
      - http://127.0.0.1:9999
      - http://host.docker.internal:9999
  NOMAD:
    ENDPOINT: http://host.docker.internal:4646
  BACKEND_CORS_ORIGINS:
    - http://localhost:8003
    - http://127.0.0.1:8003
  OAUTH:
    REDIRECT_URI: http://localhost/oauth/callback
  BASE_URI: http://localhost