default:
  AUTH_USER_MODEL: app.models.CasdoorUser
  CASDOOR:
    ENDPOINT: http://localhost:9999
    FRONT_ENDPOINT: //:9999
    ALLOWED_ISSUERS:
      - http://localhost:9999
      - http://127.0.0.1:9999
  BACKEND_CORS_ORIGINS:
    - http://localhost:8000
    - http://127.0.0.1:8000
  SEP:
    OAUTH:
      REDIRECT_URI: /oauth/callback
    SESSION:
      COOKIE_NAME: casdoorToken
    PLUGINS:
      - NAME: Schema Change
        MODULE_NAME: alters
        URI_PATH: /alters
        CSS_CLASS: alters
      - NAME: Inventory
        MODULE_NAME: inventory
        URI_PATH: /inventory
        CSS_CLASS: inventory
      - NAME: Archive
        MODULE_NAME: archives
        URI_PATH: /archives
        CSS_CLASS: archive
  TASKS:
    NOMAD:
      ENDPOINT: http://127.0.0.1:4646

development:
  SEP:
    INVENTORY_ENDPOINT: http://localhost:8000/api/inventory
    TASKS_ENDPOINT: http://localhost:8000/api/tasks
    PLUGINS:
      - NAME: Task Manager
        MODULE_NAME: tasks
        URI_PATH: /tasks
        CSS_CLASS: tasks
    SYNCERS:
      - SYNCER: PMMSyncer
        PMM:
          ENDPOINT: https://127.0.0.1:8443
          VERIFY_SSL: false
      - SYNCER: MySQLSyncer
        IGNORE_SCHEMAS:
          - sys
          - performance_schema
          - mysql
          - information_schema
  CELERY:
    BROKER_URL: "filesystem://"
    BROKER_TRANSPORT_OPTIONS:
      DATA_FOLDER_IN: data/celery/broker
      DATA_FOLDER_OUT: data/celery/broker
      PROCESSED_FOLDER: data/celery/processed
      CONTROL_FOLDER: data/celery/control
    RESULT_BACKEND: file://data/celery/results
    RESULT_PERSISTENT: true
    BEAT_SCHEDULER : 'sqlalchemy_celery_beat.schedulers:DatabaseScheduler'
    BEAT_DBURI: "sqlite:///schedule.db"

production_docker:
  CASDOOR:
    ENDPOINT: http://casdoor:8000
    CERTIFICATE_PATH: data/certs/casdoor/sep_token_jwt_key.pem
    APPLICATION_NAME: sep-app
    ORGANIZATION_NAME: sep
    ALLOWED_ISSUERS:
      - http://host.docker.internal:9999
  SEP:
    INVENTORY_ENDPOINT: https://inventory_api:9001
    TASKS_ENDPOINT: https://tasks_api:9002
    SSL_KEYFILE: data/certs/sep/localhost-cert-key.pem
    SSL_CERTFILE: data/certs/sep/localhost-cert.pem
    PROXY_HEADERS: true
    SESSION:
      SECURE: true
    SYNCERS:
      - SYNCER: PMMSyncer
        PMM:
          ENDPOINT: https://host.docker.internal:8443
          VERIFY_SSL: false
      - SYNCER: MySQLSyncer
        IGNORE_SCHEMAS:
          - sys
          - performance_schema
          - mysql
          - information_schema
  INVENTORY:
    SSL_KEYFILE: data/certs/sep/inventory_api-cert-key.pem
    SSL_CERTFILE: data/certs/sep/inventory_api-cert.pem
  TASKS:
    NOMAD:
      ENDPOINT: https://host.docker.internal:4646
      SECURE: true
      SSL_KEYFILE: data/certs/nomad/global-client-nomad-key.pem
      SSL_CERTFILE: data/certs/nomad/global-client-nomad.pem
      SSL_CAFILE: data/certs/sep-ca.pem
    SSL_KEYFILE: data/certs/sep/tasks_api-cert-key.pem
    SSL_CERTFILE: data/certs/sep/tasks_api-cert.pem
  BACKEND_CORS_ORIGINS:
    - https://localhost:8003
    - https://127.0.0.1:8003
  SSL_CAFILE: data/certs/sep-ca.pem
