default:
  AUTH_USER_MODEL: app.models.CasdoorUser
  CASDOOR:
    ENDPOINT: http://localhost:9999
    FRONT_ENDPOINT: //:9999
    CERTIFICATE_PATH: data/certs/casdoor/token_jwt_key.pem
    ALLOWED_ISSUERS:
      - http://localhost:9999
      - http://127.0.0.1:9999
  OAUTH:
    COOKIE_NAME: casdoorToken
    REDIRECT_URI: /oauth/callback
  PMM:
    ENDPOINT: https://127.0.0.1:8443
    VERIFY_SSL: false
  TEMPLATES_DIR: templates
  BACKEND_CORS_ORIGINS:
    - http://localhost:8000
    - http://127.0.0.1:8000
  NOMAD:
    ENDPOINT: http://127.0.0.1:4646
  SEP_ENDPOINT: http://localhost:8000
  PLUGINS:
    - NAME: Schema Change
      MODULE_NAME: alters
      URI_PATH: /alters
      CSS_CLASS: alters
development:
  INVENTORY_ENDPOINT: http://localhost:8000/api/inventory
  TASKS_ENDPOINT: http://localhost:8000/api/tasks
  PLUGINS:
    - NAME: Task Manager
      MODULE_NAME: tasks
      URI_PATH: /tasks
      CSS_CLASS: tasks
production_docker:
  SEP_ENDPOINT: https://0.0.0.0:8003
  INVENTORY_ENDPOINT: https://inventory_api:8001
  TASKS_ENDPOINT: https://tasks_api:8002
  PMM:
    ENDPOINT: https://host.docker.internal:8443
  CASDOOR:
    ENDPOINT: http://casdoor:8000
    ALLOWED_ISSUERS:
      - http://host.docker.internal:9999
  NOMAD:
    ENDPOINT: https://host.docker.internal:4646
    SECURE: true
    VERIFY: data/certs/sep-ca.pem
    CERT:
      - data/certs/nomad/global-client-nomad.pem
      - data/certs/nomad/global-client-nomad-key.pem
  BACKEND_CORS_ORIGINS:
    - https://localhost:8003
    - https://127.0.0.1:8003
  SSL_CAFILE: data/certs/sep-ca.pem
  SSL_KEYFILE: data/certs/sep/localhost-cert-key.pem
  SSL_CERTFILE: data/certs/sep/localhost-cert.pem
  INVENTORY_SSL_KEYFILE: data/certs/sep/inventory_api-cert-key.pem
  INVENTORY_SSL_CERTFILE: data/certs/sep/inventory_api-cert.pem
  TASKS_SSL_KEYFILE: data/certs/sep/tasks_api-cert-key.pem
  TASKS_SSL_CERTFILE: data/certs/sep/tasks_api-cert.pem
