# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Provide shared building blocks for schema-driven plugins."""

from app.sep.apps.framework.apps import (
    AppCapabilities,
    Cascade,
    StaticMount,
    TaskExecutionApp,
    Views,
)
from app.sep.apps.framework.base import BaseApp
from app.sep.apps.framework.cascade import (
    build_derived_payload,
    build_predecessor_chain_execute_body,
    build_predecessor_payload,
    cascade_create_predecessors,
    cascade_create_tasks,
    cascade_delete_predecessors,
    cascade_delete_tasks,
    cascade_update_predecessors,
    cascade_update_tasks,
    CascadeFailure,
    CascadeResult,
)
from app.sep.apps.framework.connectivity import (
    ConnectivityWarning,
    maybe_record_connectivity_warning,
    record_connectivity_warning,
)
from app.sep.apps.framework.deps import make_parent_resolver, make_task_dep
from app.sep.apps.framework.form_dsl import (
    AppFormModel,
    check_form_conformance,
    Choices,
    derive_app_schema,
    derive_form_sections,
    FieldWidget,
    Forbidden,
    FormLayout,
    FormRules,
    HostRef,
    Option,
    RemoteChoices,
    Requires,
    SchemaRef,
    SectionLayout,
    SectionRules,
    ServiceRef,
    TableRef,
    TaskFormModel,
    Ui,
)
from app.sep.apps.framework.responses import (
    BaseTaskResponse,
    build_default_task_response,
    build_task_list_responses,
    derive_create_response_model,
    dump_with_excluded_fields,
    TaskExecuteWrite,
    TaskExecutionResponse,
)
from app.sep.apps.framework.rules import (
    absent,
    all_,
    all_equal,
    all_falsy,
    all_present,
    all_truthy,
    any_,
    any_falsy,
    any_present,
    any_truthy,
    apply_conditional_rules,
    CardinalityRule,
    ConditionalRulesModel,
    evaluate_conditional_rules,
    F,
    FailRule,
    falsy,
    FieldExpr,
    FieldGate,
    none_present,
    not_,
    Predicate,
    present,
    truthy,
    xor_,
)
from app.sep.apps.framework.script_source import ScriptSource
from app.sep.apps.framework.spec import (
    assemble_envelope,
    build_run_python_task,
    EnvelopeSpec,
    resolve_refs,
    ResolvedEntities,
    RunCommandSpec,
    RunPythonSpec,
)
from app.sep.apps.framework.task_status import (
    batch_get_latest_statuses,
    extract_latest_history,
    extract_latest_task_status,
    get_task_latest_history,
    get_task_latest_status,
)

__all__ = [
    "AppCapabilities",
    "AppFormModel",
    "BaseApp",
    "BaseTaskResponse",
    "CardinalityRule",
    "Cascade",
    "CascadeFailure",
    "CascadeResult",
    "Choices",
    "ConditionalRulesModel",
    "ConnectivityWarning",
    "EnvelopeSpec",
    "F",
    "FailRule",
    "FieldExpr",
    "FieldGate",
    "FieldWidget",
    "Forbidden",
    "FormLayout",
    "FormRules",
    "HostRef",
    "Option",
    "Predicate",
    "RemoteChoices",
    "Requires",
    "ResolvedEntities",
    "RunCommandSpec",
    "RunPythonSpec",
    "SchemaRef",
    "ScriptSource",
    "SectionLayout",
    "SectionRules",
    "ServiceRef",
    "StaticMount",
    "TableRef",
    "TaskExecuteWrite",
    "TaskExecutionApp",
    "TaskExecutionResponse",
    "TaskFormModel",
    "Ui",
    "Views",
    "absent",
    "all_",
    "all_equal",
    "all_falsy",
    "all_present",
    "all_truthy",
    "any_",
    "any_falsy",
    "any_present",
    "any_truthy",
    "apply_conditional_rules",
    "assemble_envelope",
    "batch_get_latest_statuses",
    "build_default_task_response",
    "build_derived_payload",
    "build_predecessor_chain_execute_body",
    "build_predecessor_payload",
    "build_run_python_task",
    "build_task_list_responses",
    "cascade_create_predecessors",
    "cascade_create_tasks",
    "cascade_delete_predecessors",
    "cascade_delete_tasks",
    "cascade_update_predecessors",
    "cascade_update_tasks",
    "check_form_conformance",
    "derive_app_schema",
    "derive_create_response_model",
    "derive_form_sections",
    "dump_with_excluded_fields",
    "evaluate_conditional_rules",
    "extract_latest_history",
    "extract_latest_task_status",
    "falsy",
    "get_task_latest_history",
    "get_task_latest_status",
    "make_parent_resolver",
    "make_task_dep",
    "maybe_record_connectivity_warning",
    "none_present",
    "not_",
    "present",
    "record_connectivity_warning",
    "resolve_refs",
    "truthy",
    "xor_",
]
