/**
 * @sep/checksums — Checksums plugin entry point.
 *
 * This plugin is fully schema-driven. It exports:
 * - checksumsSchema: the PluginSchema definition
 * - mockChecksumTasks: mock data for development
 * - ChecksumsPlugin: a thin wrapper around SchemaDrivenPlugin
 *
 * No custom pages, hooks, or components needed — everything is
 * auto-generated by the framework's SchemaDrivenPlugin.
 */
export { checksumsSchema } from './schema';
export { mockChecksumTasks } from './mock-data';
export { ChecksumsPlugin } from './ChecksumsPlugin';
