# Copyright (C) 2025 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""React assets utilities."""

import json
import logging
from pathlib import Path

from app.sep.config import sep_settings

logger = logging.getLogger(__name__)


def get_react_assets() -> dict[str, str]:
    """Get React asset manifest for dynamic file loading.

    Reads the asset manifest file generated by React build process and returns
    a dictionary mapping entry names to their corresponding file paths.

    :return: Dictionary mapping entry names to their file paths
    :rtype: dict[str, str]

    """
    manifest_path = Path(sep_settings.STATIC_DIR) / "react" / "asset-manifest.json"
    try:
        if manifest_path.exists():
            with manifest_path.open() as f:
                return json.load(f)
        else:
            logger.warning("React manifest not found at %s", manifest_path)
            return {}
    except (OSError, json.JSONDecodeError):
        logger.exception("Error reading React manifest")
        return {}
