#!/usr/bin/env bash
# Generate this harness's per-deployment secrets (.env) and render pmm.conf
# from its committed template. Idempotent: an existing .env is kept — including
# an already-minted Grafana token — and pmm.conf is re-rendered on every run.
# SEP's own settings reach the side-car as compose environment variables, which
# outrank the profile baked into the image; nothing is mounted over it.

set -o nounset
set -o pipefail

if [[ ${DEBUG:-0} == "1" ]]; then
    set -o xtrace
fi

error() { printf '✗ %s\n' "$*" >&2; }
success() { printf '✓ %s\n' "$*" >&2; }
info() { printf 'ℹ %s\n' "$*" >&2; }

need_cmd() {
    command -v "$1" > /dev/null 2>&1 || {
        error "Missing required command: $1"
        exit 2
    }
}

need_cmd openssl
need_cmd sed
need_cmd grep

usage() {
    cat << 'EOF'
bootstrap.sh

Generate .env (PG password, SEP secret key, SEP internal token, and an empty
Grafana token slot) next to this script if it does not exist, then render
pmm.conf from pmm.conf.template. Run before the first `docker compose up -d`,
and re-run after editing the template or rotating a secret.

Options:
  -h, --help    Show this help
EOF
    exit "${1:-0}"
}

[[ $# -eq 0 ]] || case "$1" in
    -h | --help) usage 0 ;;
    *)
        error "Unknown argument: $1"
        usage 2
        ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}" || exit 1

if [[ -f .env ]]; then
    info "Keeping existing .env"
    if ! grep -q '^SEP_GRAFANA_TOKEN=' .env; then
        printf 'SEP_GRAFANA_TOKEN=\n' >> .env
        success "Added the SEP_GRAFANA_TOKEN slot to the existing .env"
    fi
else
    cat > .env << EOF
# Generated by bootstrap.sh — per-deployment feature-build secrets (gitignored)
SEP_PG_PASSWORD=$(openssl rand -hex 16)
SEP_SECRET_KEY=$(openssl rand -hex 32)
SEP_INTERNAL_TOKEN=$(openssl rand -hex 32)
# Filled in by ./mint-grafana-token.sh; empty leaves the profile's inert token
SEP_GRAFANA_TOKEN=
EOF
    chmod 600 .env
    success "Generated .env"
fi

# shellcheck disable=SC1091
source .env
: "${SEP_PG_PASSWORD:?missing in .env}" "${SEP_SECRET_KEY:?missing in .env}" "${SEP_INTERNAL_TOKEN:?missing in .env}"

# Truncate-write (cat >) keeps the target inode, so a running container's bind
# mount sees the new content without a recreate
render() {
    local template="$1" target="$2"
    sed -e "s|__SEP_BEARER_TOKEN__|${SEP_INTERNAL_TOKEN}|g" \
        "${template}" > ".render.tmp"
    cat .render.tmp > "${target}"
    rm -f .render.tmp
    success "Rendered ${target}"
}

render pmm.conf.template pmm.conf

info "Next: docker compose up -d   (or: podman compose up -d)"
