#!/usr/bin/env bash
# Generate this harness's per-deployment secrets (.env) and render pmm.conf
# from its committed template. Idempotent: an existing .env is kept — including
# an already-minted Grafana token — and pmm.conf is re-rendered on every run.
# SEP's own settings reach the side-car as compose environment variables, which
# outrank the profile baked into the image; nothing is mounted over it.

set -o nounset
set -o pipefail

if [[ ${DEBUG:-0} == "1" ]]; then
    set -o xtrace
fi

error() { printf '✗ %s\n' "$*" >&2; }
success() { printf '✓ %s\n' "$*" >&2; }
info() { printf 'ℹ %s\n' "$*" >&2; }

# Runs a command with xtrace suspended, restoring it on return (local -).
# DEBUG=1 traces every expansion, and the secrets below reach the wrapped
# commands as arguments, as sourced assignments and as rendered file contents —
# tracing those would print every per-deployment secret.
without_xtrace() {
    local -
    set +o xtrace
    "$@"
}

need_cmd() {
    command -v "$1" > /dev/null 2>&1 || {
        error "Missing required command: $1"
        exit 2
    }
}

need_cmd openssl
need_cmd sed
need_cmd grep

usage() {
    cat << 'EOF'
bootstrap.sh

Generate .env (PG password, SEP secret key, SEP internal token, the three
sep-mysql passwords, and an empty Grafana token slot) next to this script if it
does not exist, then render pmm.conf from pmm.conf.template. An existing .env
is kept and any slot it predates is appended. Run before the first
`docker compose up -d`, and re-run after editing the template or rotating a
secret.

Options:
  -h, --help    Show this help
EOF
    exit "${1:-0}"
}

[[ $# -eq 0 ]] || case "$1" in
    -h | --help) usage 0 ;;
    *)
        error "Unknown argument: $1"
        usage 2
        ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}" || exit 1

# Arguments: the slot name, and the value to append when the slot is absent
ensure_slot() {
    local name="$1" value="$2"
    grep -q "^${name}=" .env && return 0
    # A hand-edited .env may lack the trailing newline the append needs
    [[ -z $(tail -c1 .env) ]] || printf '\n' >> .env
    printf '%s=%s\n' "${name}" "${value}" >> .env
    success "Added the ${name} slot to the existing .env"
}

# Wrapped by without_xtrace at the call site: the generated passwords reach
# ensure_slot as arguments
seed_missing_slots() {
    local slot
    ensure_slot SEP_GRAFANA_TOKEN ""
    for slot in SEP_MYSQL_ROOT_PASSWORD SEP_MYSQL_BACKUP_PASSWORD SEP_MYSQL_PMM_PASSWORD; do
        ensure_slot "${slot}" "$(openssl rand -hex 16)"
    done
}

if [[ -f .env ]]; then
    info "Keeping existing .env"
    chmod 600 .env
    without_xtrace seed_missing_slots
else
    cat > .env << EOF
# Generated by bootstrap.sh — per-deployment feature-build secrets (gitignored)
SEP_PG_PASSWORD=$(openssl rand -hex 16)
SEP_SECRET_KEY=$(openssl rand -hex 32)
SEP_INTERNAL_TOKEN=$(openssl rand -hex 32)
# Filled in by ./mint-grafana-token.sh; empty leaves the profile's inert token
SEP_GRAFANA_TOKEN=
# sep-mysql: root, the sep_backup user both backup payloads authenticate as,
# and the PMM exporters' monitoring user. Rotating these after first boot needs
# the sep-mysql-data volume dropped — the datadir keeps the original passwords.
SEP_MYSQL_ROOT_PASSWORD=$(openssl rand -hex 16)
SEP_MYSQL_BACKUP_PASSWORD=$(openssl rand -hex 16)
SEP_MYSQL_PMM_PASSWORD=$(openssl rand -hex 16)
EOF
    chmod 600 .env
    success "Generated .env"
fi

# Wrapped rather than run at top level: sourcing traces every assignment in
# .env, and ${VAR:?} puts the value itself into the trace line
load_env() {
    # shellcheck disable=SC1091
    source .env
    : "${SEP_PG_PASSWORD:?missing in .env}" "${SEP_SECRET_KEY:?missing in .env}" "${SEP_INTERNAL_TOKEN:?missing in .env}"
    : "${SEP_MYSQL_ROOT_PASSWORD:?missing in .env}" "${SEP_MYSQL_BACKUP_PASSWORD:?missing in .env}" \
        "${SEP_MYSQL_PMM_PASSWORD:?missing in .env}"
}

without_xtrace load_env

# Truncate-write (cat >) keeps the target inode, so a running container's bind
# mount sees the new content without a recreate
render() {
    local template="$1" target="$2"
    local rendered
    rendered="$(sed -e "s|__SEP_BEARER_TOKEN__|${SEP_INTERNAL_TOKEN}|g" \
        "${template}")" || {
        error "Render failed for ${target}; leaving it unchanged"
        return 1
    }
    [[ -n ${rendered} ]] || {
        error "Render produced empty output for ${target}; leaving it unchanged"
        return 1
    }
    printf '%s\n' "${rendered}" > "${target}" || {
        error "Could not write ${target}"
        return 1
    }
    success "Rendered ${target}"
}

without_xtrace render pmm.conf.template pmm.conf || exit 1

info "Next: docker compose --profile mysql up -d --build   (or: podman compose ...)"
info "Omit --profile mysql to bring up just pmm-server and sep-sidecar"
