#!/usr/bin/env bash
# Generate this harness's per-deployment secrets (.env). Idempotent: an existing
# .env is kept, and any slot it predates is appended. PMM owns every remaining
# SEP secret — it writes them into the pmm-sep volume, which the side-car
# reads as files; nothing secret reaches the side-car as environment.

set -o nounset
set -o pipefail

if [[ ${DEBUG:-0} == "1" ]]; then
    set -o xtrace
fi

error() { printf '✗ %s\n' "$*" >&2; }
success() { printf '✓ %s\n' "$*" >&2; }
info() { printf 'ℹ %s\n' "$*" >&2; }

# Runs a command with xtrace suspended, restoring it on return (local -).
# DEBUG=1 traces every expansion, and the secrets below reach the wrapped
# commands both as arguments and as sourced assignments — tracing those would
# print every per-deployment secret.
without_xtrace() {
    local -
    set +o xtrace
    "$@"
}

need_cmd() {
    command -v "$1" > /dev/null 2>&1 || {
        error "Missing required command: $1"
        exit 2
    }
}

need_cmd openssl
need_cmd grep

usage() {
    cat << 'EOF'
bootstrap.sh

Generate .env (the PostgreSQL password PMM provisions SEP's role with, and the
three sep-mysql passwords) next to this script if it does not exist. An existing
.env is kept and any slot it predates is appended. Run before the first
`docker compose up -d`, and re-run after rotating a secret.

Options:
  -h, --help    Show this help
EOF
    exit "${1:-0}"
}

[[ $# -eq 0 ]] || case "$1" in
    -h | --help) usage 0 ;;
    *)
        error "Unknown argument: $1"
        usage 2
        ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}" || exit 1

ensure_slot() {
    local name="$1" value="$2"
    grep -q "^${name}=" .env && return 0
    # A hand-edited .env may lack the trailing newline the append needs
    [[ -z $(tail -c1 .env) ]] || printf '\n' >> .env
    printf '%s=%s\n' "${name}" "${value}" >> .env
    success "Added the ${name} slot to the existing .env"
}

# Wrapped by without_xtrace at the call site: the generated passwords reach
# ensure_slot as arguments
seed_missing_slots() {
    local slot
    for slot in SEP_MYSQL_ROOT_PASSWORD SEP_MYSQL_BACKUP_PASSWORD SEP_MYSQL_PMM_PASSWORD; do
        ensure_slot "${slot}" "$(openssl rand -hex 16)"
    done
}

if [[ -f .env ]]; then
    info "Keeping existing .env"
    chmod 600 .env
    without_xtrace seed_missing_slots
else
    cat > .env << EOF
# Generated by bootstrap.sh — per-deployment feature-build secrets (gitignored)
SEP_PG_PASSWORD=$(openssl rand -hex 16)
# Rotating these after first boot needs the sep-mysql-data volume dropped — the
# datadir keeps the original passwords
SEP_MYSQL_ROOT_PASSWORD=$(openssl rand -hex 16)
SEP_MYSQL_BACKUP_PASSWORD=$(openssl rand -hex 16)
SEP_MYSQL_PMM_PASSWORD=$(openssl rand -hex 16)
EOF
    chmod 600 .env
    success "Generated .env"
fi

# Wrapped rather than run at top level: sourcing traces every assignment in
# .env, and ${VAR:?} puts the value itself into the trace line
load_env() {
    # shellcheck disable=SC1091
    source .env
    : "${SEP_PG_PASSWORD:?missing in .env}"
    : "${SEP_MYSQL_ROOT_PASSWORD:?missing in .env}" "${SEP_MYSQL_BACKUP_PASSWORD:?missing in .env}" \
        "${SEP_MYSQL_PMM_PASSWORD:?missing in .env}"
}

without_xtrace load_env

info "Next: docker compose --profile mysql up -d --build   (or: podman compose ...)"
info "Omit --profile mysql to bring up just pmm-server and sep-sidecar"
