#!/usr/bin/env tsx
/**
 * OpenAPI → TypeScript codegen.
 *
 * Iterates over SPECS and writes one `src/generated/{name}.ts` per entry.
 * If SEP ever publishes a single merged spec, collapse SPECS to one entry.
 * The source may be an HTTP URL (live backend) or a local file path.
 *
 * Usage:
 *   pnpm --filter @sep/api codegen
 *   CODEGEN_BASE_URL=http://localhost:8000 pnpm --filter @sep/api codegen
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

type SpecSource = { name: string; source: string };

const BASE_URL = process.env.CODEGEN_BASE_URL ?? 'http://localhost:8000';

const SPECS: SpecSource[] = [
  { name: 'main', source: `${BASE_URL}/openapi.json` },
  { name: 'inventory', source: `${BASE_URL}/api/inventory/openapi.json` },
  { name: 'tasks', source: `${BASE_URL}/api/tasks/openapi.json` },
  { name: 'sep', source: `${BASE_URL}/api/sep/openapi.json` },
];

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(HERE, '..', 'src', 'generated');

const HEADER = [
  '/**',
  ' * This file is auto-generated by `pnpm --filter @sep/api codegen`.',
  ' * Do not edit by hand — regenerate from the source OpenAPI spec.',
  ' */',
  '',
].join('\n');

async function toURL(source: string): Promise<URL | string> {
  if (source.startsWith('http://') || source.startsWith('https://')) {
    return new URL(source);
  }
  return path.resolve(process.cwd(), source);
}

async function generateOne(spec: SpecSource): Promise<void> {
  const input = await toURL(spec.source);
  const ast = await openapiTS(input, {
    enum: false,
    immutable: false,
  });
  const body = astToString(ast);
  const outPath = path.join(OUT_DIR, `${spec.name}.ts`);
  await writeFile(outPath, HEADER + body, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[codegen] wrote ${path.relative(process.cwd(), outPath)}`);
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  for (const spec of SPECS) {
    try {
      await generateOne(spec);
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error(`[codegen] FAILED ${spec.name} (${spec.source})`);
      throw err;
    }
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
