"""add_primary_unique_key_field

Revision ID: 0efdd39ccb46
Revises: 6761fa809e84
Create Date: 2024-11-21 13:42:08.304023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0efdd39ccb46'
down_revision: Union[str, None] = '6761fa809e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('primary_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('table', sa.Column('unique_keys', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'unique_keys')
    op.drop_column('table', 'primary_key')
    # ### end Alembic commands ###
