# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Create Inventory tables

Revision ID: 8e95b4982efb
Revises:
Create Date: 2024-09-24 17:01:44.575366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e95b4982efb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('PMM', name='sourceenum'), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_external_id'), 'node', ['external_id'], unique=False)
    op.create_index('ix_node_external_id_source', 'node', ['external_id', 'source'], unique=True)
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', name='servicetypeenum'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_external_id'), 'service', ['external_id'], unique=False)
    op.create_index('ix_service_external_id_node_id', 'service', ['external_id', 'node_id'], unique=True)
    op.create_index(op.f('ix_service_node_id'), 'service', ['node_id'], unique=False)
    op.create_table('schema',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schema_name_service_id', 'schema', ['name', 'service_id'], unique=True)
    op.create_index(op.f('ix_schema_service_id'), 'schema', ['service_id'], unique=False)
    op.create_table('table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['schema.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_table_name_schema_id', 'table', ['name', 'schema_id'], unique=True)
    op.create_index(op.f('ix_table_schema_id'), 'table', ['schema_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_schema_id'), table_name='table')
    op.drop_index('ix_table_name_schema_id', table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_schema_service_id'), table_name='schema')
    op.drop_index('ix_schema_name_service_id', table_name='schema')
    op.drop_table('schema')
    op.drop_index(op.f('ix_service_node_id'), table_name='service')
    op.drop_index('ix_service_external_id_node_id', table_name='service')
    op.drop_index(op.f('ix_service_external_id'), table_name='service')
    op.drop_table('service')
    op.drop_index('ix_node_external_id_source', table_name='node')
    op.drop_index(op.f('ix_node_external_id'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
