"""add_keys_field_for_table

Revision ID: 83707159e945
Revises: 6761fa809e84
Create Date: 2024-11-25 09:46:09.289392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83707159e945'
down_revision: Union[str, None] = '6761fa809e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('keys', sa.JSON(), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'keys')
    # ### end Alembic commands ###
