"""Create unique index for service port by node id

Revision ID: 6761fa809e84
Revises: 8e95b4982efb
Create Date: 2024-10-15 17:24:47.692296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6761fa809e84'
down_revision: Union[str, None] = '8e95b4982efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_port_node_id', 'service', ['port', 'node_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_port_node_id', table_name='service')
    # ### end Alembic commands ###
