"""Make ServiceTypeEnum non-native

Revision ID: 2f39f63eb355
Revises: 4df7d4433322
Create Date: 2025-07-10 18:11:17.823221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f39f63eb355'
down_revision: Union[str, None] = '4df7d4433322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column(
            'type',
            type_=sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', 'PROXYSQL', 'HAPROXY', name='servicetypeenum', native_enum=False),
            existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column(
            'type',
            existing_type=sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', 'PROXYSQL', 'HAPROXY', name='servicetypeenum', native_enum=False),
            type_=sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', 'PROXYSQL', 'HAPROXY', name='servicetypeenum', native_enum=True),
            existing_nullable=False,
            postgresql_using="type::servicetypeenum"
        )
    # ### end Alembic commands ###
