# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Add new PMM Service fields

Revision ID: ceea7494ff83
Revises: 2f39f63eb355
Create Date: 2025-10-03 15:31:53.895329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ceea7494ff83'
down_revision: Union[str, None] = '2f39f63eb355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('cluster', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('service', sa.Column('replication_set', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('service', sa.Column('custom_labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'custom_labels')
    op.drop_column('service', 'replication_set')
    op.drop_column('service', 'cluster')
    # ### end Alembic commands ###
