"""Update ServiceTypeEnum

Revision ID: 4df7d4433322
Revises: b422e3cb9b35
Create Date: 2025-02-14 18:06:35.318220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4df7d4433322'
down_revision: Union[str, None] = 'b422e3cb9b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column(
            'type',
            existing_type=sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', name='servicetypeenum'),
            type_=sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', 'PROXYSQL', 'HAPROXY', name='servicetypeenum', native_enum=True),
            existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column(
            'type',
            existing_type=sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', 'PROXYSQL', 'HAPROXY', name='servicetypeenum', native_enum=True),
            type_=sa.Enum('MYSQL', 'POSTGRESQL', 'MONGODB', 'EXTERNAL', name='servicetypeenum'),
            existing_nullable=False
        )
    # ### end Alembic commands ###
