"""Add_PMM_extra_labels

Revision ID: 876d2ffe5d1c
Revises: 2f39f63eb355
Create Date: 2025-10-02 18:08:33.254505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '876d2ffe5d1c'
down_revision: Union[str, None] = '2f39f63eb355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('cluster', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('service', sa.Column('replication_set', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('service', sa.Column('custom_labels', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'custom_labels')
    op.drop_column('service', 'replication_set')
    op.drop_column('service', 'cluster')
    # ### end Alembic commands ###
