# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""add system observation tables

Revision ID: b73c0110ad55
Revises: ceea7494ff83
Create Date: 2026-06-04 10:05:46.423092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b73c0110ad55'
down_revision: Union[str, None] = 'ceea7494ff83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hostsystemobservation',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('node_id', sa.Integer(), nullable=False),
        sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('installed_packages', sa.JSON(), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_hostsystemobservation_node_id'),
        'hostsystemobservation',
        ['node_id'],
        unique=True,
    )
    op.create_table(
        'servicesystemobservation',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.Column('db_engine_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_servicesystemobservation_service_id'),
        'servicesystemobservation',
        ['service_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_servicesystemobservation_service_id'),
        table_name='servicesystemobservation',
    )
    op.drop_table('servicesystemobservation')
    op.drop_index(
        op.f('ix_hostsystemobservation_node_id'),
        table_name='hostsystemobservation',
    )
    op.drop_table('hostsystemobservation')
    # ### end Alembic commands ###
