/**
 * Copyright (C) 2026 Percona LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @sep/checksums — Checksums plugin entry point.
 *
 * This plugin is fully schema-driven. It exports:
 * - checksumsSchema: the PluginSchema definition
 * - mockChecksumTasks: mock data for development
 * - ChecksumsPlugin: a thin wrapper around SchemaDrivenPlugin
 *
 * No custom pages, hooks, or components needed — everything is
 * auto-generated by the framework's SchemaDrivenPlugin.
 */
export { checksumsSchema } from './schema';
export { mockChecksumTasks } from './mock-data';
export { ChecksumsPlugin } from './ChecksumsPlugin';
