"""Create SyncInstance table

Revision ID: 75e02f5b2c40
Revises: 
Create Date: 2024-10-01 09:51:39.487806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75e02f5b2c40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syncinstance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('inventory_type', sa.Enum('INVENTORY', 'NODE', 'SERVICE', 'SCHEMA', 'TABLE', name='syncinventorytypeenum'), nullable=False),
    sa.Column('task_history_id', sa.Integer(), nullable=True),
    sa.Column('syncer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('INVENTORY', 'NODE', 'SERVICE', 'SCHEMA', 'TABLE', name='syncinventorytypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncinstance_inventory_id'), 'syncinstance', ['inventory_id'], unique=False)
    op.create_index('ix_syncinstance_inventory_id_inventory_type_status', 'syncinstance', ['inventory_id', 'inventory_type', 'status'], unique=False)
    op.create_index(op.f('ix_syncinstance_inventory_type'), 'syncinstance', ['inventory_type'], unique=False)
    op.create_index('ix_syncinstance_inventory_type_status', 'syncinstance', ['inventory_type', 'status'], unique=False)
    op.create_index(op.f('ix_syncinstance_status'), 'syncinstance', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncinstance_status'), table_name='syncinstance')
    op.drop_index('ix_syncinstance_inventory_type_status', table_name='syncinstance')
    op.drop_index(op.f('ix_syncinstance_inventory_type'), table_name='syncinstance')
    op.drop_index('ix_syncinstance_inventory_id_inventory_type_status', table_name='syncinstance')
    op.drop_index(op.f('ix_syncinstance_inventory_id'), table_name='syncinstance')
    op.drop_table('syncinstance')
    # ### end Alembic commands ###
