"""Remove task_history_id field

Revision ID: eeac2926bbea
Revises: 7f4dec8bc76a
Create Date: 2024-10-08 20:47:04.961743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eeac2926bbea'
down_revision: Union[str, None] = '7f4dec8bc76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('syncitem', 'task_history_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syncitem', sa.Column('task_history_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
