"""Create sync tables

Revision ID: cfa3844a3e4c
Revises: 
Create Date: 2024-10-02 18:42:06.353642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfa3844a3e4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syncinstance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('syncer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syncitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('inventory_type', sa.Enum('INVENTORY', 'NODE', 'SERVICE', 'SCHEMA', 'TABLE', name='syncinventorytypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='syncstatusenum'), nullable=False),
    sa.Column('task_history_id', sa.Integer(), nullable=True),
    sa.Column('sync_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_instance_id'], ['syncinstance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncitem_inventory_id'), 'syncitem', ['inventory_id'], unique=False)
    op.create_index('ix_syncitem_inventory_id_inventory_type_status', 'syncitem', ['inventory_id', 'inventory_type', 'status'], unique=False)
    op.create_index(op.f('ix_syncitem_inventory_type'), 'syncitem', ['inventory_type'], unique=False)
    op.create_index('ix_syncitem_inventory_type_status', 'syncitem', ['inventory_type', 'status'], unique=False)
    op.create_index(op.f('ix_syncitem_status'), 'syncitem', ['status'], unique=False)
    op.create_index(op.f('ix_syncitem_sync_instance_id'), 'syncitem', ['sync_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncitem_sync_instance_id'), table_name='syncitem')
    op.drop_index(op.f('ix_syncitem_status'), table_name='syncitem')
    op.drop_index('ix_syncitem_inventory_type_status', table_name='syncitem')
    op.drop_index(op.f('ix_syncitem_inventory_type'), table_name='syncitem')
    op.drop_index('ix_syncitem_inventory_id_inventory_type_status', table_name='syncitem')
    op.drop_index(op.f('ix_syncitem_inventory_id'), table_name='syncitem')
    op.drop_table('syncitem')
    op.drop_table('syncinstance')
    # ### end Alembic commands ###
