# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Create sync tables

Revision ID: 7f4dec8bc76a
Revises:
Create Date: 2024-10-07 14:50:33.721820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f4dec8bc76a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syncinstance',
    sa.Column('syncer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syncitem',
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Enum('INVENTORY', 'NODE', 'SERVICE', 'SCHEMA', 'TABLE', name='syncinventoryentitytypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='syncstatusenum'), nullable=False),
    sa.Column('task_history_id', sa.Integer(), nullable=True),
    sa.Column('sync_instance_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sync_instance_id'], ['syncinstance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncitem_entity_id'), 'syncitem', ['entity_id'], unique=False)
    op.create_index('ix_syncitem_entity_id_entity_type_status', 'syncitem', ['entity_id', 'entity_type', 'status'], unique=False)
    op.create_index(op.f('ix_syncitem_entity_type'), 'syncitem', ['entity_type'], unique=False)
    op.create_index('ix_syncitem_entity_type_status', 'syncitem', ['entity_type', 'status'], unique=False)
    op.create_index(op.f('ix_syncitem_status'), 'syncitem', ['status'], unique=False)
    op.create_index(op.f('ix_syncitem_sync_instance_id'), 'syncitem', ['sync_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncitem_sync_instance_id'), table_name='syncitem')
    op.drop_index(op.f('ix_syncitem_status'), table_name='syncitem')
    op.drop_index('ix_syncitem_entity_type_status', table_name='syncitem')
    op.drop_index(op.f('ix_syncitem_entity_type'), table_name='syncitem')
    op.drop_index('ix_syncitem_entity_id_entity_type_status', table_name='syncitem')
    op.drop_index(op.f('ix_syncitem_entity_id'), table_name='syncitem')
    op.drop_table('syncitem')
    op.drop_table('syncinstance')
    # ### end Alembic commands ###
