"""Create Snippet table

Revision ID: 7f933ab5f212
Revises: eeac2926bbea
Create Date: 2025-03-02 00:38:17.593896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f933ab5f212'
down_revision: Union[str, None] = 'eeac2926bbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('md5_digest', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_approved_at'), 'snippet', ['approved_at'], unique=False)
    op.create_index(op.f('ix_snippet_filename'), 'snippet', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippet_filename'), table_name='snippet')
    op.drop_index(op.f('ix_snippet_approved_at'), table_name='snippet')
    op.drop_table('snippet')
    # ### end Alembic commands ###
