"""Add index for syncinstance.syncer

Revision ID: 810c31754b54
Revises: 9307f0f5ee54
Create Date: 2026-03-02 16:12:33.126181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '810c31754b54'
down_revision: Union[str, None] = '9307f0f5ee54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_syncinstance_syncer'), 'syncinstance', ['syncer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncinstance_syncer'), table_name='syncinstance')
    # ### end Alembic commands ###
