# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""add seppluginperiodictask

Revision ID: 64f10ead74f6
Revises: e5c224619161
Create Date: 2026-06-15 17:25:38.544837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64f10ead74f6'
down_revision: Union[str, None] = 'e5c224619161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seppluginperiodictask',
    sa.Column('periodic_task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seppluginperiodictask_app_key'), 'seppluginperiodictask', ['app_key'], unique=False)
    op.create_index(op.f('ix_seppluginperiodictask_periodic_task_name'), 'seppluginperiodictask', ['periodic_task_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seppluginperiodictask_periodic_task_name'), table_name='seppluginperiodictask')
    op.drop_index(op.f('ix_seppluginperiodictask_app_key'), table_name='seppluginperiodictask')
    op.drop_table('seppluginperiodictask')
    # ### end Alembic commands ###
