#!/usr/bin/env python3
# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Emit per-upload-selection variants of ``xtrabackup_payload``.

``xtrabackup_payload`` ships to Nomad as a parameterized-job payload and must stay
under the hard 16 KiB dispatch limit, but it carries all three upload-provider
classes while a task only ever exercises the provider(s) named in ``form.upload``.
This generator reads the canonical payload, drops the regions the selection cannot
reach, and writes one variant per selection so each dispatch buys back the bytes
its unused providers would have cost.

The canonical payload *is* the all-providers variant, so it is never rewritten --
it stays the complete, human-edited source. The other seven selections are
generated beside it.

Regions are delimited in the canonical source by ``# GEN:UPLOAD-BEGIN <provider>``
/ ``# GEN:UPLOAD-END <provider>`` marker comments. Markers cost nothing at dispatch
because the executor minifies the payload before sending it.

Usage::

    python scripts/gen_xtrabackup_payload_variants.py           # rewrite variants
    python scripts/gen_xtrabackup_payload_variants.py --check    # fail on drift
"""

import argparse
import ast
import builtins
import importlib.util
import itertools
import re
import sys
from pathlib import Path
from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[1]
PAYLOAD_DIR = REPO_ROOT / "app/sep/apps/mysql_backups"


def _load_naming_rule() -> ModuleType:
    """Return the app module owning the provider order and variant filenames.

    Loaded by path rather than imported: ``app.sep.apps.mysql_backups.__init__``
    builds the FastAPI app, which a pre-commit hook must not have to stand up.

    :return: The ``payload_variants`` module.
    """
    path = PAYLOAD_DIR / "payload_variants.py"
    spec = importlib.util.spec_from_file_location("payload_variants", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load the variant naming rule from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_NAMING = _load_naming_rule()

#: Upload providers in the order the canonical payload declares them, owned by the
#: app module so the generator and the dispatcher cannot disagree on a filename.
PROVIDERS: tuple[str, ...] = _NAMING.PROVIDERS
variant_name = _NAMING.variant_name

CANONICAL_SOURCE = PAYLOAD_DIR / _NAMING.CANONICAL_PAYLOAD_NAME

#: Names each provider owns exclusively in the canonical payload. A variant that
#: omits the provider must not mention any of them -- that is how the generator
#: catches a region boundary drawn too narrowly.
EXCLUSIVE_NAMES = {
    "rsync": ("RsyncUploadProvider", "RSYNC_BIN"),
    "s3": ("S3UploadProvider", "boto3", "ClientError"),
    "gsutil": ("GSUploadProvider", "GCLOUD_BIN", "tempfile"),
}

BEGIN = "# GEN:UPLOAD-BEGIN"
END = "# GEN:UPLOAD-END"

_MARKER = re.compile(r"^\s*# GEN:UPLOAD-(?P<kind>BEGIN|END) (?P<provider>\S+)\s*$")

_BANNER = (
    "# Generated by scripts/gen_xtrabackup_payload_variants.py -- do not edit.\n"
    "# Canonical source: app/sep/apps/mysql_backups/xtrabackup_payload\n"
    "# Upload providers carried by this variant: {providers}\n"
)


class RegionError(RuntimeError):
    """Raise when the canonical source's region markers are malformed."""


def selections() -> list[tuple[str, ...]]:
    """Return every upload selection, from the empty set to all providers.

    :return: The eight provider tuples, each in :data:`PROVIDERS` order.
    """
    return [
        combo
        for size in range(len(PROVIDERS) + 1)
        for combo in itertools.combinations(PROVIDERS, size)
    ]


def render(source: str, providers: tuple[str, ...]) -> str:
    """Return ``source`` reduced to the regions ``providers`` can reach.

    Marker lines are dropped whether or not their region is kept, so a variant
    never looks like a second canonical source. Runs of blank lines left behind by
    a dropped region are collapsed to two, which keeps the output deterministic --
    the property ``--check`` depends on.

    :param source: The canonical payload source.
    :param providers: The providers the variant keeps.
    :return: The variant source, newline-terminated.
    :raises RegionError: On a nested, unterminated, or unopened marker region.
    """
    keep = set(providers)
    out: list[str] = []
    open_provider: str | None = None
    for lineno, line in enumerate(source.split("\n"), start=1):
        match = _MARKER.match(line)
        if match is None:
            if open_provider is None or open_provider in keep:
                out.append(line)
            continue
        kind, provider = match.group("kind"), match.group("provider")
        if provider not in PROVIDERS:
            raise RegionError(f"unknown provider {provider!r} on line {lineno}")
        if kind == "BEGIN":
            if open_provider is not None:
                raise RegionError(
                    f"nested region for {provider!r} on line {lineno}; "
                    f"{open_provider!r} is still open"
                )
            open_provider = provider
        else:
            if open_provider != provider:
                raise RegionError(f"unopened END for {provider!r} on line {lineno}")
            open_provider = None
    if open_provider is not None:
        raise RegionError(f"unterminated region for {open_provider!r}")

    text = re.sub(r"\n{3,}", "\n\n\n", "\n".join(out))
    return text.rstrip("\n") + "\n"


def with_banner(text: str, providers: tuple[str, ...]) -> str:
    """Return ``text`` with the generated-file banner inserted after the shebang.

    :param text: The rendered variant source.
    :param providers: The providers the variant carries.
    :return: The variant source with its banner.
    """
    banner = _BANNER.format(providers=", ".join(providers) if providers else "none")
    lines = text.split("\n")
    return "\n".join([lines[0], banner.rstrip("\n"), *lines[1:]])


#: Module-level names the interpreter supplies, which no source line binds.
_MODULE_DUNDERS = frozenset(
    {"__file__", "__name__", "__doc__", "__spec__", "__loader__", "__package__"}
)


def bound_names(tree: ast.AST) -> set[str]:
    """Return every name the module binds anywhere.

    Scope is deliberately flattened: the check this feeds asks whether a name
    survives *somewhere* in the variant, not whether each reference resolves under
    Python's scoping rules. Flattening keeps it free of false alarms at the cost of
    missing genuine scope errors, which are the canonical payload's problem, not the
    generator's.

    :param tree: The parsed variant source.
    :return: The bound names, including imports, definitions, and arguments.
    """
    bound: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store | ast.Del):
            bound.add(node.id)
        elif isinstance(node, ast.Import | ast.ImportFrom):
            bound.update((a.asname or a.name).split(".")[0] for a in node.names)
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
            bound.add(node.name)
            args = getattr(node, "args", None)
            if args is not None:
                bound.update(
                    a.arg
                    for a in (
                        *args.posonlyargs,
                        *args.args,
                        *args.kwonlyargs,
                        *([args.vararg] if args.vararg else []),
                        *([args.kwarg] if args.kwarg else []),
                    )
                )
        elif isinstance(node, ast.Lambda):
            bound.update(a.arg for a in (*node.args.posonlyargs, *node.args.args))
        elif isinstance(node, ast.ExceptHandler) and node.name:
            bound.add(node.name)
        elif isinstance(node, ast.Global | ast.Nonlocal):
            bound.update(node.names)
        elif isinstance(node, ast.MatchAs | ast.MatchStar) and node.name:
            bound.add(node.name)
    return bound


def validate(text: str, omitted: tuple[str, ...], name: str) -> None:
    """Check a rendered variant parses and strands no reference to an omitted provider.

    A syntactically valid variant that still names a class it no longer defines
    would only fail at backup runtime, on a customer host -- so the generator
    refuses to write it. Two passes catch that: an unbound-name sweep, which needs
    no bookkeeping and so covers names added to a region later, and an
    :data:`EXCLUSIVE_NAMES` intersection, which additionally catches a stranded name
    the sweep cannot see because something else still binds it.

    :param text: The rendered variant source.
    :param omitted: The providers this variant dropped.
    :param name: The variant filename, for error messages.
    :raises RegionError: When the variant does not parse, references a name nothing
        in it binds, or mentions a name belonging exclusively to an omitted provider.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError as exc:
        raise RegionError(f"{name} does not parse: {exc}") from exc

    loaded = {
        node.id
        for node in ast.walk(tree)
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load)
    }
    referenced = loaded | {
        node.value.id
        for node in ast.walk(tree)
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name)
    }
    for node in ast.walk(tree):
        if isinstance(node, ast.Import | ast.ImportFrom):
            referenced.update((a.asname or a.name).split(".")[0] for a in node.names)

    for provider in omitted:
        stranded = sorted(set(EXCLUSIVE_NAMES[provider]) & referenced)
        if stranded:
            raise RegionError(
                f"{name} omits {provider!r} but still references {stranded}; "
                "widen that provider's GEN:UPLOAD region in the canonical payload"
            )

    unbound = sorted(loaded - bound_names(tree) - set(dir(builtins)) - _MODULE_DUNDERS)
    if unbound:
        raise RegionError(
            f"{name} references {unbound}, which nothing in it defines; "
            "widen the GEN:UPLOAD region that owns those names"
        )


def build(source: str, providers: tuple[str, ...]) -> str:
    """Render, banner and validate the variant carrying ``providers``.

    :param source: The canonical payload source.
    :param providers: The providers the variant carries.
    :return: The variant source ready to write.
    :raises RegionError: When the rendered variant is invalid.
    """
    name = variant_name(providers)
    text = with_banner(render(source, providers), providers)
    validate(text, tuple(p for p in PROVIDERS if p not in providers), name)
    return text


def main(argv: list[str] | None = None) -> int:
    """Rewrite or check the generated ``xtrabackup_payload`` variants.

    :param argv: The CLI arguments (defaults to ``sys.argv``).
    :return: ``0`` when every variant is in sync (or was rewritten); ``1`` when
        ``--check`` finds drift or a variant fails validation.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when any variant has drifted from the canonical payload",
    )
    args = parser.parse_args(argv)

    source = CANONICAL_SOURCE.read_text(encoding="utf-8")
    if BEGIN not in source:
        print(
            f"{CANONICAL_SOURCE.relative_to(REPO_ROOT)} carries no {BEGIN} markers",
            file=sys.stderr,
        )
        return 1

    drift: list[Path] = []
    rewritten: list[Path] = []
    generated = 0
    for providers in selections():
        path = CANONICAL_SOURCE.parent / variant_name(providers)
        if path == CANONICAL_SOURCE:
            continue
        generated += 1
        try:
            text = build(source, providers)
        except RegionError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1
        rel = path.relative_to(REPO_ROOT)
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            print(f"unchanged  {rel}")
        elif args.check:
            drift.append(path)
            print(f"drifted    {rel}")
        else:
            path.write_text(text, encoding="utf-8")
            rewritten.append(path)
            print(f"rewrote    {rel}")

    if args.check:
        if drift:
            rels = [str(p.relative_to(REPO_ROOT)) for p in drift]
            print(
                f"xtrabackup payload variant drift: {rels}; regenerate with "
                "`python scripts/gen_xtrabackup_payload_variants.py`",
                file=sys.stderr,
            )
            return 1
        print(f"All {generated} xtrabackup payload variants are in sync.")
        return 0

    print(
        f"Synced {generated} xtrabackup payload variants: "
        f"{len(rewritten)} rewritten, {generated - len(rewritten)} already in sync."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
