name: Setup Python job
description: Checkout repo, install Poetry, setup Python
inputs:
  python-version:
    description: Version of Python to use
    required: true
    default: "3.11"
  cache:
    description: Type of cache to use
    required: false
    default: "poetry"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry==2.1.2
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache }}
