# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Ask each Alembic track what its autogenerate sweep makes of the beat tables.

Every track configures ``include_object`` at its own ``env.py``, so all three
need the coincident-store state :func:`create_beat_tables` builds, and each asks
its sweep the question :func:`tables_mentioned` asks.
"""

__all__ = ["autogenerate_diffs", "create_beat_tables", "tables_mentioned"]

from collections.abc import Collection
from typing import Any

from alembic import command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected
from sqlalchemy import create_engine
from sqlalchemy_celery_beat.session import ModelBase


def create_beat_tables(sync_url: str) -> None:
    """Create the ``sqlalchemy_celery_beat`` schedule tables at ``sync_url``.

    The engine carries the same ``schema_translate_map`` the library installs in
    :meth:`~sqlalchemy_celery_beat.session.SessionManager.create_session`; without
    it ``create_all`` emits ``celery_schema.``-qualified DDL, which SQLite rejects.

    :param sync_url: A synchronous SQLAlchemy URL for the track's test database.
    """
    engine = create_engine(sync_url).execution_options(
        schema_translate_map={"celery_schema": None}
    )
    try:
        ModelBase.metadata.create_all(engine)
    finally:
        engine.dispose()


def autogenerate_diffs(cfg: Config) -> list[tuple[Any, ...]]:
    """Return the operations ``cfg``'s track proposes, through the CI entry point.

    ``command.check`` reports through an exception and returns nothing, so this
    inverts it into the diff list both outcomes describe.

    :param cfg: The track's Alembic config, addressing a database already
        upgraded to ``heads``.
    :return: Every proposed operation, empty when the sweep found none.
    :raises CommandError: When the sweep cannot run at all, such as an
        unresolvable revision or a database behind its head. Only the
        diffs-detected subclass answers the question; the rest mean a broken
        caller.
    """
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as detected:
        return detected.diffs
    return []


def tables_mentioned(diffs: list[tuple[Any, ...]], names: Collection[str]) -> list[str]:
    """Return which of ``names`` the proposed operations refer to.

    Callers ask this rather than asserting that a track's sweep came back empty.
    ``target_metadata`` is the process-wide ``SQLModel.metadata``, so what a
    track's sweep reports depends on which other tracks' models the collected
    tests have imported into it. In a whole-suite run, which is what CI does,
    each track sees the other tracks' tables and reports them as missing. That
    is absent when ``alembic --name <track>`` runs for real, and it is unrelated
    to the beat tables either way.

    Matching the rendered operations rather than the ``remove_table`` entries
    alone also catches an index or constraint leaking out for an excluded table.
    The name is matched quoted, as ``repr`` renders it, so that
    ``celery_periodictask`` does not report itself present on the strength of
    ``celery_periodictaskchanged`` alone.

    :param diffs: Proposed operations, as :func:`autogenerate_diffs` returns them.
    :param names: The table names to look for.
    :return: The names the operations mention, sorted.
    """
    rendered = repr(diffs)
    return sorted(name for name in names if f"'{name}'" in rendered)
