# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Define Pydantic models for the Inventory plugin's schedule UI and API responses."""

from typing import Any

from pydantic import BaseModel, model_validator

from app.core.celery.models import CrontabSchedule, IntervalSchedule
from app.core.utils.fields import EmptyStrToNone, UTCDatetime
from app.sep.utils.forms import parse_crontab_form_fields, parse_interval_form_fields
from app.tasks.models import INVENTORY_SYNC_TASK_NAME


class PluginTaskResponse(BaseModel):
    """Represent a single plugin task entry returned by ``GET /api/apps/inventory/``.

    :param name: Machine-readable task identifier (e.g. ``"inventory-sync"``).
    :type name: str
    :param display_name: Human-readable label for the schedule UI.
    :type display_name: str
    """

    name: str
    display_name: str


class InventorySyncScheduleCreateForm(BaseModel):
    """Define the form-data shape for attaching an inventory-sync schedule.

    Mirror the ``interval_every`` / ``interval_period`` / ``cron_expression``
    / ``cron_timezone`` field names used by the schedule template
    (``templates/inventory/partials/sync-schedule-edit-form.html.j2``) so the
    existing template's input names continue to work, and add a ``syncer``
    field that gets persisted into ``execute_request.meta`` as
    ``{"syncer": <fully qualified name>}`` when set.

    :param syncer: Optional fully qualified syncer name (e.g.
        ``"app.sep.sync.syncers.pmm.PMMSyncer"``). When set, the schedule
        targets that syncer only; when unset, the schedule runs every
        configured syncer.
    :type syncer: str | None
    :param enabled: Whether the schedule is enabled.
    :type enabled: bool | EmptyStrToNone
    :param interval: Populated by the validator from ``interval_every`` and
        ``interval_period`` form fields.
    :type interval: IntervalSchedule | EmptyStrToNone
    :param crontab: Populated by the validator from ``cron_expression`` and
        ``cron_timezone`` form fields.
    :type crontab: CrontabSchedule | EmptyStrToNone
    :param start_time: Optional UTC start time.
    :type start_time: UTCDatetime | EmptyStrToNone
    """

    syncer: str | EmptyStrToNone = None
    enabled: bool | EmptyStrToNone = None
    interval: IntervalSchedule | EmptyStrToNone = None
    crontab: CrontabSchedule | EmptyStrToNone = None
    start_time: UTCDatetime | EmptyStrToNone = None

    @model_validator(mode="before")
    @classmethod
    def normalize_form(cls, data: Any) -> Any:
        """Transform flat form fields into structured ``interval`` / ``crontab``.

        Share the dict-construction helpers with
        :class:`app.sep.tasks.PeriodicTaskRequest.set_period` (both reach into
        :mod:`app.sep.utils.forms`) so the form accepts the exact same input
        shape as the schedule template. Do not
        validate that exactly one schedule mode is provided — the route
        performs that check so a friendly HTTP 400 message can be raised.

        :param data: Raw input data from the form parser.
        :type data: Any
        :return: The data with parsed ``interval`` / ``crontab`` keys added.
        :rtype: Any
        """
        if not isinstance(data, dict):
            return data
        if "interval_every" in data and "interval_period" in data:
            data["interval"] = parse_interval_form_fields(data)
        if "cron_expression" in data and "cron_timezone" in data:
            data["crontab"] = parse_crontab_form_fields(data)
        return data

    def to_periodic_task_payload(self) -> dict[str, Any]:
        """Build the JSON payload for the Tasks API ``POST /<task>/periodic/``.

        Drop the ``syncer`` field from the top-level payload and place it inside
        ``execute_request.meta`` instead so it is persisted on the periodic-task
        row's ``kwargs`` and forwarded to the callable when the schedule fires.
        Include ``task: "inventory-sync"`` so the autogenerated periodic-task
        name (a hash over the encoded ``kwargs``) matches the value produced by
        the generic ``/periodic/`` proxy and a duplicate-attach attempt
        collides instead of silently creating a second row.

        :return: A JSON-serialisable payload ready to forward to the Tasks API.
        :rtype: dict[str, Any]
        """
        payload = self.model_dump(
            exclude_none=True,
            exclude_unset=True,
            exclude={"syncer"},
        )
        payload["task"] = INVENTORY_SYNC_TASK_NAME
        if self.syncer:
            payload["execute_request"] = {"meta": {"syncer": self.syncer}}
        return payload
