# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Define Pydantic models for the Inventory plugin's schedule UI and API responses."""

from __future__ import annotations

from typing import Any, Literal, Self

from pydantic import BaseModel, Field, model_validator

from app.core.celery.models import CrontabSchedule, IntervalSchedule
from app.core.utils.fields import EmptyStrToNone, UTCDatetime
from app.sep.utils.forms import parse_crontab_form_fields, parse_interval_form_fields

INVENTORY_SYNC_TASK_NAME = "inventory-sync"
MAX_TOPOLOGY_SHARDS = 8


class PluginTaskResponse(BaseModel):
    """Represent a single plugin task entry returned by ``GET /api/apps/inventory/``.

    :param name: Machine-readable task identifier (e.g. ``"inventory-sync"``).
    :type name: str
    :param display_name: Human-readable label for the schedule UI.
    :type display_name: str
    """

    name: str
    display_name: str


class InventorySyncScheduleCreateForm(BaseModel):
    """Define the form-data shape for attaching an inventory-sync schedule.

    Mirror the ``interval_every`` / ``interval_period`` / ``cron_expression``
    / ``cron_timezone`` field names used by the schedule template
    (``templates/inventory/partials/sync-schedule-edit-form.html.j2``) so the
    existing template's input names continue to work, and add a ``syncer``
    field that gets persisted into ``execute_request.meta`` as
    ``{"syncer": <fully qualified name>}`` when set.

    :param syncer: Optional fully qualified syncer name (e.g.
        ``"app.sep.sync.syncers.pmm.PMMSyncer"``). When set, the schedule
        targets that syncer only; when unset, the schedule runs every
        configured syncer.
    :type syncer: str | None
    :param enabled: Whether the schedule is enabled.
    :type enabled: bool | EmptyStrToNone
    :param interval: Populated by the validator from ``interval_every`` and
        ``interval_period`` form fields.
    :type interval: IntervalSchedule | EmptyStrToNone
    :param crontab: Populated by the validator from ``cron_expression`` and
        ``cron_timezone`` form fields.
    :type crontab: CrontabSchedule | EmptyStrToNone
    :param start_time: Optional UTC start time.
    :type start_time: UTCDatetime | EmptyStrToNone
    """

    syncer: str | EmptyStrToNone = None
    enabled: bool | EmptyStrToNone = None
    interval: IntervalSchedule | EmptyStrToNone = None
    crontab: CrontabSchedule | EmptyStrToNone = None
    start_time: UTCDatetime | EmptyStrToNone = None

    @model_validator(mode="before")
    @classmethod
    def normalize_form(cls, data: Any) -> Any:
        """Transform flat form fields into structured ``interval`` / ``crontab``.

        Share the dict-construction helpers with
        :class:`app.sep.tasks.PeriodicTaskRequest.set_period` (both reach into
        :mod:`app.sep.utils.forms`) so the form accepts the exact same input
        shape as the schedule template. Do not
        validate that exactly one schedule mode is provided — the route
        performs that check so a friendly HTTP 400 message can be raised.

        :param data: Raw input data from the form parser.
        :type data: Any
        :return: The data with parsed ``interval`` / ``crontab`` keys added.
        :rtype: Any
        """
        if not isinstance(data, dict):
            return data
        if "interval_every" in data and "interval_period" in data:
            data["interval"] = parse_interval_form_fields(data)
        if "cron_expression" in data and "cron_timezone" in data:
            data["crontab"] = parse_crontab_form_fields(data)
        return data

    def to_periodic_task_payload(self) -> dict[str, Any]:
        """Build the JSON payload for the Tasks API ``POST /<task>/periodic/``.

        Drop the ``syncer`` field from the top-level payload and place it inside
        ``execute_request.meta`` instead so it is persisted on the periodic-task
        row's ``kwargs`` and forwarded to the callable when the schedule fires.
        Include ``task: "inventory-sync"`` so the autogenerated periodic-task
        name (a hash over the encoded ``kwargs``) matches the value produced by
        the generic ``/periodic/`` proxy and a duplicate-attach attempt
        collides instead of silently creating a second row.

        :return: A JSON-serialisable payload ready to forward to the Tasks API.
        :rtype: dict[str, Any]
        """
        payload = self.model_dump(
            exclude_none=True,
            exclude_unset=True,
            exclude={"syncer"},
        )
        payload["task"] = INVENTORY_SYNC_TASK_NAME
        if self.syncer:
            payload["execute_request"] = {"meta": {"syncer": self.syncer}}
        return payload


class TopologyCollectWrite(BaseModel):
    """Describe the request body for ``POST /topology/collect``.

    :param shards: Number of executor hosts to dispatch in parallel. Hosts
        are split round-robin across the chosen executors. Capped at
        :data:`MAX_TOPOLOGY_SHARDS`.
    :type shards: int
    :param executor_host: Optional explicit executor. Must be used with
        ``shards=1`` because it selects a single-shard run.
    :type executor_host: str | None
    :param connect_timeout: Per-host MySQL TCP connect timeout (seconds).
    :type connect_timeout: int
    :param read_timeout: Per-host MySQL read/write timeout (seconds).
    :type read_timeout: int
    """

    shards: int = Field(default=1, ge=1, le=MAX_TOPOLOGY_SHARDS)
    executor_host: str | None = None
    connect_timeout: int = Field(default=5, ge=1, le=60)
    read_timeout: int = Field(default=10, ge=1, le=120)

    @model_validator(mode="after")
    def _reject_executor_with_multiple_shards(self) -> Self:
        if self.executor_host and self.shards != 1:
            raise ValueError("executor_host requires shards=1")
        return self


class TopologyCollectResponse(BaseModel):
    """Represent the response body for ``POST /topology/collect``.

    ``task_history_ids`` lists the dispatched ``run-python`` tasks the
    frontend then polls (``/result``) and tails (``/stream``) to
    assemble the topology graph. ``targets`` echoes the executor hosts
    the work was sharded across so the UI can surface where the
    collection ran.

    :param task_history_ids: Created task history ids, one per shard.
    :type task_history_ids: list[int]
    :param targets: Executor hosts selected for topology collection.
    :type targets: list[str]
    :param host_count: Number of MySQL hosts included in the collection.
    :type host_count: int
    :param shard_count: Number of dispatched topology shards.
    :type shard_count: int
    """

    task_history_ids: list[int]
    targets: list[str]
    host_count: int
    shard_count: int


class TopologyResultResponse(BaseModel):
    """Represent the response body for ``GET /topology/result``.

    ``status`` is ``running`` while any of the underlying tasks is
    still pending, ``ok`` once every task has finished, and ``failed``
    when at least one task failed and produced no usable output.
    ``graph`` is the merged React-Flow graph; ``pending_task_ids``
    lists the still-running tasks for the UI's progress chip, and
    ``failed_task_ids`` lets the UI warn when only some shards failed.

    :param status: Aggregate topology collection status.
    :type status: Literal["running", "ok", "failed"]
    :param graph: Merged React-Flow graph when collection output is ready.
    :type graph: dict[str, Any] | None
    :param pending_task_ids: Task ids still pending or running.
    :type pending_task_ids: list[int]
    :param failed_task_ids: Terminal task ids that did not finish successfully.
    :type failed_task_ids: list[int]
    """

    status: Literal["running", "ok", "failed"]
    graph: dict[str, Any] | None = None
    pending_task_ids: list[int] = Field(default_factory=list)
    failed_task_ids: list[int] = Field(default_factory=list)
