#!/usr/bin/env tsx
/**
 * Copyright (C) 2026 Percona LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Generate the shell ICON_BY_KEY map from the backend NavIcon vocabulary.
 *
 * Reads the `nav_icons__NavIcon` enum from the committed OpenAPI spec (the same
 * fixture the api type codegen consumes) and emits
 * `src/generated/appNavIcons.ts`, so adding a sidebar icon is a backend-only
 * edit plus a codegen re-run. All resolution logic lives in the typed, unit-
 * tested `src/appNavIcons.codegen.ts`; this wrapper is pure I/O.
 *
 * Usage:
 *   pnpm --filter @sep/shell codegen
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveNavIcon } from '../src/appNavIcons.codegen';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SPEC = path.resolve(HERE, '..', '..', 'api', 'specs', 'sep.json');
const OUT_DIR = path.resolve(HERE, '..', 'src', 'generated');
const OUT = path.join(OUT_DIR, 'appNavIcons.ts');

const HEADER = [
  '/**',
  ' * This file is auto-generated by `pnpm --filter @sep/shell codegen`.',
  ' * Do not edit by hand — regenerate from the source OpenAPI spec.',
  ' */',
  '',
].join('\n');

/** Quote an object key only when it is not a bare JS identifier. */
function quoteKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : `'${key}'`;
}

async function main(): Promise<void> {
  const spec = JSON.parse(await readFile(SPEC, 'utf8'));
  const keys: string[] = spec.components.schemas.nav_icons__NavIcon.enum;

  const muiImports: string[] = [];
  const brandNames: string[] = [];
  const entries: string[] = [];

  for (const key of keys) {
    const { module, importName } = resolveNavIcon(key);
    if (module === '@percona/percona-ui') {
      brandNames.push(importName);
    } else {
      muiImports.push(`import ${importName} from '${module}';`);
    }
    entries.push(`  ${quoteKey(key)}: ${importName},`);
  }

  const imports = [
    "import type { SepComponents } from '@sep/api';",
    ...muiImports,
    ...(brandNames.length
      ? [`import { ${brandNames.join(', ')} } from '@percona/percona-ui';`]
      : []),
    "import type { NavIcon } from '../contexts/navigation';",
  ];

  const body = [
    ...imports,
    '',
    "export const ICON_BY_KEY: Record<SepComponents['schemas']['nav_icons__NavIcon'], NavIcon> = {",
    ...entries,
    '};',
    '',
  ].join('\n');

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT, HEADER + body, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[codegen] wrote ${path.relative(process.cwd(), OUT)}`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
