# Main CI workflow

name: CI

on:
  pull_request:
    branches:
    - main
    types:
    - labeled
    - ready_for_review
    - synchronize
    - unlabeled
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  do-not-merge-fail:
    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled as 'do not merge'
        run: |
          echo "This PR is labeled as 'do not merge' and cannot be merged'
          exit 1

  precommit:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: ./.github/actions/setup-python-job

      - name: Perform pre-commit checks
        env:
          POETRY: poetry
        run: |
          make run-pre-commit

  python:
    if: ${{ github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'python') }}
    uses: ./.github/workflows/python.yaml
    needs:
      - precommit

  build:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    needs:
      - python
    steps:
      - name: Checkout codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare environment
        run: |
          sudo apt update -qqy
          sudo apt install -qqy podman buildah
          systemctl --user start podman
          echo "DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock" >> "$GITHUB_ENV"

      - name: Build container image
        env:
          RELEASE_VER: HEAD
        run: |
          buildah build -f Containerfile.base --compress --force-rm --squash --no-cache --format oci --memory 100M --isolation rootless --tag "sep:builder"
          make pack
          buildah build -f Containerfile --compress --force-rm --squash --no-cache --format oci --memory 100M --isolation rootless --tag "sep:${RELEASE_VER}"
          podman run --rm --entrypoint /bin/sh --timeout 10 "sep:${RELEASE_VER}" -c 'sleep 3'
