name: Labels

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  autolabel:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
...
