# Main CI workflow

name: Python

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  POETRY: poetry

jobs:
  audit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: workspace
      - name: Install poetry
        run: pipx install poetry==1.8.4
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python }}
          cache: poetry
      - name: Perform audit
        working-directory: ./workspace
        run: RUFF_OUTPUT_FORMAT=github make audit

  test:
    needs: [audit]
    name: test (${{ matrix.python }})
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: workspace
      - name: Install poetry
        run: pipx install poetry==1.8.4
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python }}
          cache: poetry
      - name: Install test dependencies
        run: poetry install --with syncmysql
      - name: Run tests
        working-directory: ./workspace
        run: make test

  build:
    needs: [audit, test]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout codebase
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: workspace
    - name: Install poetry
      run: pipx install poetry==1.8.4
    - name: Setup Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ matrix.python }}
        cache: poetry
    - name: Build package
      working-directory: ./workspace
      run: make build
