# Main CI workflow

name: Python

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  POETRY: poetry

jobs:
  bandit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
      - name: Run bandit
        run: make bandit

  check_migrations:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
      - name: Check migrations
        run: CASDOOR__CLIENT_SECRET=notatoken CASDOOR__CLIENT_ID=notatoken make checkmigrations

  test:
    name: test (${{ matrix.python }})
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11.9", "3.12.3", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
          cache: poetry
      - name: Install test dependencies
        run: poetry install --with syncmysql
      - name: Run tests
        run: make test
      - name: Generate coverage comment data
        id: coverage_comment
        if: matrix.python == '3.11.9' && github.event_name == 'pull_request'
        uses: py-cov-action/python-coverage-comment-action@7188638f871f721a365d644f505d1ff3df20d683 # v3.40
        with:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload coverage comment artifact
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt

  build:
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
      - name: Build package
        run: make build
