# Main CI workflow

name: Python

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  POETRY: poetry

jobs:
  audit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
      - name: Perform audit
        working-directory: ./workspace
        run: RUFF_OUTPUT_FORMAT=github make audit
        shell: bash

  check_migrations:
    needs: [audit]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
      - name: Check migrations
        working-directory: ./workspace
        run: CASDOOR__CLIENT_SECRET=notatoken CASDOOR__CLIENT_ID=notatoken make checkmigrations
        shell: bash

  test:
    needs: [audit, check_migrations]
    name: test (${{ matrix.python }})
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        working-directory: ./workspace
        run: poetry install --with syncmysql
      - name: Run tests
        working-directory: ./workspace
        run: make test
        shell: bash

  build:
    needs: [audit, test, check_migrations]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: ./.github/actions/setup-python-job
        with:
          python-version: ${{ matrix.python }}
      - name: Build package
        working-directory: ./workspace
        run: make build
        shell: bash
