# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""OM bootstrap payload -- PoC, single host, single-member replica set only.

Rides the same ``run-python`` job as :mod:`app.sep.apps.om_inventory.payload.probe`
(see that module's docstring for the dispatch mechanics -- ``NOMAD_META_CONFIG`` in,
NDJSON on stdout out). Unlike the probe, this one **writes**: it installs PSMDB,
generates configuration, and initializes a replica set on the host it runs on. It
exists to answer one question before PMM-15347's design questions (project/cluster
shape, secrets storage, partial-failure policy, multi-host orchestration) are settled:
does Nomad's ``raw_exec`` dispatch -- the same channel the read-only probe already
proves works -- actually have enough privilege to install a package, write to
``/etc``, and manage a systemd unit? This payload is the cheapest way to find out.

Deliberately out of scope, all tracked in ``PMM-15347/questions.md`` rather than
guessed at here: TLS (config always renders ``net.tls`` off), multi-host replica
sets, sharded clusters, project/cluster assignment, and any rollback on failure. A
single host either ends up with a working one-member replica set or it doesn't; nothing
here cleans up a partial install.

**Debian/Ubuntu only.** The percona-release setup mirrors
``psmdb/Dockerfile``'s verified apt sequence. A RHEL/yum path is not implemented --
detected and reported as an explicit, named failure rather than attempted and left to
fail confusingly partway through.

Config, in ``NOMAD_META_CONFIG``::

    {
      "replica_set_name": "rs-orders-prod",
      "mongodb_version": "7.0.8",
      "data_path": "/var/lib/mongodb",
      "log_path": "/var/log/mongodb/mongod.log",
      "port": 27017,
      "bind_ip": "0.0.0.0",
      "member_host": "app-prod-01",
      "key_file_path": "/etc/mongodb/keyfile",
      "key_file_b64": "<base64, generated by the dispatcher>",
      "admin_username": "admin",
      "admin_password_b64": "<base64, generated by the dispatcher>"
    }

Every ``key_*_b64`` value is base64 only to survive JSON transport through
``NOMAD_META_CONFIG`` cleanly -- it is not encryption. Where these values actually
live before and after this runs is PMM-15347/questions.md Q7, unresolved; for this
PoC the dispatcher (``bootstrap.py`` at the app level, not this payload) generates
them fresh per run and this payload is the only other thing that ever sees them.

Prints one NDJSON line per stage to stdout, matching the ``05-bootstrap.png`` mockup's
four-stage breakdown: ``connect``, ``install_packages``, ``configure_mongod``,
``initialize_replica_set``. Each line is
``{"stage": ..., "status": "started"|"ok"|"failed", "detail": ..., "at": <epoch>}``.
A ``failed`` line ends the run: later stages assume earlier ones succeeded, so this
payload exits 1 the moment one does, unlike the probe's "keep going, report what
broke" contract -- there is no honest partial state for "mongod is configured but
was never started."
"""

import base64
import json
import os
import subprocess
import sys
import time

STATUS_STARTED = "started"
STATUS_OK = "ok"
STATUS_FAILED = "failed"

#: Bound on how long any one shell command here may take. Generous relative to
#: probe.py's 15s: ``apt-get install`` genuinely takes longer than a ``ps`` call.
COMMAND_TIMEOUT_SEC = 300
#: How long to wait for mongod to start accepting connections after the service is
#: started, seconds.
MONGOD_READY_TIMEOUT_SEC = 60
MONGOD_READY_POLL_SEC = 2
#: How long to wait for the single-member replica set to elect a primary, seconds.
#: Should be fast -- one voting member has nothing to negotiate with.
REPL_PRIMARY_TIMEOUT_SEC = 30
REPL_PRIMARY_POLL_SEC = 1

#: Verified working sequence -- see psmdb/Dockerfile. Not re-derived here: this is
#: the same package the sandbox's own database images install from.
PERCONA_RELEASE_DEB_URL = (
    "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
)
#: Documented RPM equivalent of the verified Debian path above. Not exercised in this
#: workspace -- see the module docstring's "Debian/Ubuntu only" note.
PERCONA_RELEASE_RPM_URL = "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"

DEFAULT_PORT = 27017
DEFAULT_DATA_PATH = "/var/lib/mongodb"
DEFAULT_LOG_PATH = "/var/log/mongodb/mongod.log"
DEFAULT_BIND_IP = "0.0.0.0"
DEFAULT_KEY_FILE_PATH = "/etc/mongodb/keyfile"
DEFAULT_CONF_PATH = "/etc/mongod.conf"
#: The user/group PSMDB's packaging creates and mongod runs as on Debian/Ubuntu.
MONGOD_OS_USER = "mongod"


class StageFailed(Exception):
    """Raised by a stage function to end the run with a named cause."""


def load_config():
    """Return the task config parsed from ``NOMAD_META_CONFIG``.

    :return: The config mapping.
    """
    raw = os.environ.get("NOMAD_META_CONFIG")
    if not raw:
        print("NOMAD_META_CONFIG is not set", file=sys.stderr)
        sys.exit(1)
    try:
        return json.loads(raw)
    except ValueError as err:
        print(f"NOMAD_META_CONFIG is not valid JSON: {err}", file=sys.stderr)
        sys.exit(1)


def emit(stage, status, detail=None):
    """Print one NDJSON progress line for a stage.

    :param stage: The stage name, one of the four in the module docstring.
    :param status: ``started``, ``ok``, or ``failed``.
    :param detail: A short human-readable note, or ``None``.
    """
    print(
        json.dumps(
            {"stage": stage, "status": status, "detail": detail, "at": int(time.time())},
            default=str,
        ),
        flush=True,
    )


def run(args, *, timeout=COMMAND_TIMEOUT_SEC, input_text=None):
    """Run ``args`` and return its stdout, raising :class:`StageFailed` on failure.

    Unlike probe.py's best-effort ``run_command``, a failure here is fatal: every
    caller in this payload is a step later ones depend on, not an optional fact.

    :param args: The argv list to execute.
    :param timeout: Seconds before the command is killed.
    :param input_text: Text piped to the command's stdin, or ``None``.
    :return: The command's stdout.
    :raises StageFailed: On a non-zero exit, a timeout, or the binary being missing.
    """
    try:
        completed = subprocess.run(
            args,
            capture_output=True,
            text=True,
            timeout=timeout,
            input=input_text,
            check=False,
        )
    except FileNotFoundError as err:
        raise StageFailed(f"{args[0]}: not found ({err})") from err
    except subprocess.SubprocessError as err:
        raise StageFailed(f"{' '.join(args)}: {err}") from err
    if completed.returncode != 0:
        tail = (completed.stderr or completed.stdout or "").strip()[-2000:]
        raise StageFailed(f"{' '.join(args)}: exit {completed.returncode}: {tail}")
    return completed.stdout


def detect_os_family():
    """Return ``"debian"``, ``"redhat"``, or ``None`` from ``/etc/os-release``.

    :return: The OS family, or ``None`` when unrecognised.
    """
    os_release = {}
    try:
        with open("/etc/os-release", encoding="utf-8") as handle:
            for line in handle:
                if "=" not in line:
                    continue
                key, _, value = line.partition("=")
                os_release[key.strip()] = value.strip().strip('"')
    except OSError:
        return None
    id_like = f"{os_release.get('ID', '')} {os_release.get('ID_LIKE', '')}".lower()
    if "debian" in id_like or "ubuntu" in id_like:
        return "debian"
    if "rhel" in id_like or "fedora" in id_like or "centos" in id_like:
        return "redhat"
    return None


def percona_series_for_version(version):
    """Return the ``percona-release`` series for a MongoDB major version.

    ``"7.0.8"`` -> ``"psmdb-70"``, matching the argument
    ``psmdb/Dockerfile``'s ``PSMDB_REPO`` build arg takes. Only the major version
    selects the series; PSMDB does not ship parallel repos per minor version.

    :param version: The requested MongoDB version, e.g. ``"7.0.8"``.
    :return: The series name.
    :raises StageFailed: When ``version`` does not start with a recognisable major
        version number.
    """
    major = (version or "").split(".", 1)[0]
    if not major.isdigit():
        raise StageFailed(f"cannot derive a percona-release series from version {version!r}")
    return f"psmdb-{major}0"


def ensure_percona_release(config, os_family):
    """Install and pin ``percona-release`` to the requested PSMDB series.

    Idempotent: ``percona-release enable-only`` is safe to run against a host that
    already has it configured for a different series (that is the documented
    in-place-upgrade path, per ``psmdb/Dockerfile``'s comment on this exact command).

    :param config: The task config.
    :param os_family: ``"debian"`` or ``"redhat"``, from :func:`detect_os_family`.
    :raises StageFailed: On any step failing, or an unsupported OS family.
    """
    series = percona_series_for_version(config.get("mongodb_version"))
    if os_family == "debian":
        deb_path = "/tmp/percona-release.deb"
        run(["curl", "-fsSL", "-o", deb_path, PERCONA_RELEASE_DEB_URL])
        run(["apt-get", "update"])
        run(["apt-get", "install", "-y", "--no-install-recommends", deb_path])
    elif os_family == "redhat":
        run(["yum", "install", "-y", PERCONA_RELEASE_RPM_URL])
    else:
        raise StageFailed(
            "unsupported or undetected OS family -- this payload installs on "
            "Debian/Ubuntu (apt) or RHEL-family (yum) hosts only"
        )
    run(["percona-release", "enable-only", series, "release"])


def install_packages(os_family):
    """Install the PSMDB server package.

    :param os_family: ``"debian"`` or ``"redhat"``.
    :raises StageFailed: On the package manager failing.
    """
    package_manager = ["apt-get"] if os_family == "debian" else ["yum"]
    if os_family == "debian":
        run(["apt-get", "update"])
    run(
        [
            *package_manager,
            "install",
            "-y",
            *(["--no-install-recommends"] if os_family == "debian" else []),
            "percona-server-mongodb-server",
        ]
    )


def write_keyfile(config):
    """Write the intra-cluster auth keyFile and lock down its permissions.

    MongoDB's keyFile format is the base64 *text* itself, used directly as the
    shared secret string (6-1024 base64 characters) -- not a base64 encoding of
    some other binary payload to decode back out. ``key_file_b64`` is already in
    exactly that shape (see ``bootstrap.py``'s ``generate_keyfile_b64``), so it
    is written to disk as-is. Decoding it first, which an earlier version of
    this function did, writes raw binary that trips mongod's own keyfile
    parser: ``yaml-cpp: error ... unknown escape character`` -- it does not even
    fail as "wrong length," it fails trying to parse the binary as text.

    MongoDB refuses to start with a keyFile that is group- or world-readable, so the
    ``chmod`` here is not cosmetic -- an over-permissive file fails mongod's own
    startup check.

    :param config: The task config, carrying ``key_file_path`` and ``key_file_b64``.
    :raises StageFailed: On a missing key, or the file operations failing.
    """
    path = config.get("key_file_path") or DEFAULT_KEY_FILE_PATH
    encoded = config.get("key_file_b64")
    if not encoded:
        raise StageFailed("config carries no key_file_b64")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="ascii") as handle:
        handle.write(encoded)
    os.chmod(path, 0o400)
    try:
        run(["chown", f"{MONGOD_OS_USER}:{MONGOD_OS_USER}", path])
    except StageFailed:
        # Non-fatal: some images create the mongod user only when the package
        # installs, which by this point it already has -- but a hardened image
        # might restrict chown itself. mongod will fail its own startup check
        # loudly if ownership is actually wrong, which is a clearer signal than
        # this payload guessing at every possible restriction up front.
        pass


#: Rendered with ``str.format`` rather than a templating dependency -- this payload
#: stays stdlib-only, matching probe.py. authorization is always "enabled": keyFile
#: auth without SCRAM authorization would leave the cluster unauthenticated, which
#: the ticket's "Only keyFile is available for intra-cluster authentication" does not
#: ask for -- keyFile is the *intra-cluster* mechanism, SCRAM is client auth, and this
#: PoC always turns both on together.
MONGOD_CONF_TEMPLATE = """\
storage:
  dbPath: {data_path}
systemLog:
  destination: file
  path: {log_path}
  logAppend: true
net:
  port: {port}
  bindIp: {bind_ip}
security:
  authorization: enabled
  keyFile: {key_file_path}
replication:
  replSetName: {replica_set_name}
"""


def render_mongod_conf(config):
    """Write ``/etc/mongod.conf`` and create the data/log directories.

    :param config: The task config.
    :raises StageFailed: On the file/directory operations failing.
    """
    data_path = config.get("data_path") or DEFAULT_DATA_PATH
    log_path = config.get("log_path") or DEFAULT_LOG_PATH
    rendered = MONGOD_CONF_TEMPLATE.format(
        data_path=data_path,
        log_path=log_path,
        port=config.get("port") or DEFAULT_PORT,
        bind_ip=config.get("bind_ip") or DEFAULT_BIND_IP,
        key_file_path=config.get("key_file_path") or DEFAULT_KEY_FILE_PATH,
        replica_set_name=config["replica_set_name"],
    )
    os.makedirs(data_path, exist_ok=True)
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    for path in (data_path, os.path.dirname(log_path)):
        try:
            run(["chown", "-R", f"{MONGOD_OS_USER}:{MONGOD_OS_USER}", path])
        except StageFailed:
            pass  # same reasoning as write_keyfile's chown
    with open(DEFAULT_CONF_PATH, "w", encoding="utf-8") as handle:
        handle.write(rendered)


def start_service():
    """Enable and (re)start the ``mongod`` systemd unit.

    :raises StageFailed: When systemd cannot start the unit -- the most likely place
        a bad config (bad path, port already bound) surfaces.
    """
    run(["systemctl", "enable", "mongod"])
    run(["systemctl", "restart", "mongod"])


def wait_for_mongod(config):
    """Poll until mongod accepts connections, or raise on timeout.

    :param config: The task config.
    :raises StageFailed: If mongod is not accepting connections within
        :data:`MONGOD_READY_TIMEOUT_SEC`.
    """
    from pymongo import MongoClient
    from pymongo.errors import PyMongoError

    port = config.get("port") or DEFAULT_PORT
    deadline = time.time() + MONGOD_READY_TIMEOUT_SEC
    last_error = None
    while time.time() < deadline:
        try:
            client = MongoClient(
                f"mongodb://127.0.0.1:{port}/?directConnection=true",
                serverSelectionTimeoutMS=2000,
            )
            client.admin.command("ping")
            client.close()
            return
        except PyMongoError as err:
            last_error = err
            time.sleep(MONGOD_READY_POLL_SEC)
    raise StageFailed(
        f"mongod did not accept connections within {MONGOD_READY_TIMEOUT_SEC}s: "
        f"{last_error}"
    )


def initiate_replica_set(config):
    """Call ``rs.initiate()`` and create the admin user via the localhost exception.

    Single-member only for this PoC: the member array has exactly one entry, so
    there is no election to reason about and no priority-pin trick to borrow from
    ``psmdb/scripts/cluster-init.sh`` (that trick exists to make a *multi*-member
    election land on a chosen node -- moot with one voter).

    The localhost exception (creating the first user over an unauthenticated
    connection from the node itself, before any user exists) is the same mechanism
    ``psmdb/scripts/cluster-init.sh`` uses -- see that script for the multi-member
    case this borrows from.

    :param config: The task config.
    :raises StageFailed: On the initiate or user-creation command failing, or the
        replica set never electing a primary.
    """
    from pymongo import MongoClient
    from pymongo.errors import PyMongoError

    port = config.get("port") or DEFAULT_PORT
    member_host = config.get("member_host")
    if not member_host:
        raise StageFailed("config carries no member_host")

    client = MongoClient(
        f"mongodb://127.0.0.1:{port}/?directConnection=true",
        serverSelectionTimeoutMS=5000,
    )
    try:
        try:
            client.admin.command(
                "replSetInitiate",
                {
                    "_id": config["replica_set_name"],
                    "members": [
                        {"_id": 0, "host": f"{member_host}:{port}"},
                    ],
                },
            )
        except PyMongoError as err:
            raise StageFailed(f"replSetInitiate failed: {err}") from err

        deadline = time.time() + REPL_PRIMARY_TIMEOUT_SEC
        is_primary = False
        while time.time() < deadline:
            hello = client.admin.command("hello")
            if hello.get("isWritablePrimary"):
                is_primary = True
                break
            time.sleep(REPL_PRIMARY_POLL_SEC)
        if not is_primary:
            raise StageFailed(
                f"no primary elected within {REPL_PRIMARY_TIMEOUT_SEC}s of initiate"
            )

        username = config.get("admin_username") or "admin"
        password_b64 = config.get("admin_password_b64")
        if not password_b64:
            raise StageFailed("config carries no admin_password_b64")
        try:
            password = base64.b64decode(password_b64).decode("utf-8")
        except (ValueError, TypeError) as err:
            raise StageFailed(f"admin_password_b64 is not valid base64: {err}") from err

        try:
            client.admin.command(
                "createUser",
                username,
                pwd=password,
                roles=[{"role": "root", "db": "admin"}],
            )
        except PyMongoError as err:
            raise StageFailed(f"createUser failed: {err}") from err
    finally:
        client.close()


def main():
    """Run the four bootstrap stages in order, stopping at the first failure."""
    config = load_config()
    for required in ("replica_set_name", "mongodb_version", "member_host"):
        if not config.get(required):
            print(f"NOMAD_META_CONFIG is missing required field {required!r}", file=sys.stderr)
            sys.exit(1)

    emit("connect", STATUS_STARTED)
    os_family = detect_os_family()
    if os_family is None:
        emit("connect", STATUS_FAILED, "could not determine OS family from /etc/os-release")
        sys.exit(1)
    emit("connect", STATUS_OK, f"os_family={os_family}")

    emit("install_packages", STATUS_STARTED)
    try:
        ensure_percona_release(config, os_family)
        install_packages(os_family)
    except StageFailed as err:
        emit("install_packages", STATUS_FAILED, str(err))
        sys.exit(1)
    emit("install_packages", STATUS_OK)

    emit("configure_mongod", STATUS_STARTED)
    try:
        write_keyfile(config)
        render_mongod_conf(config)
        start_service()
        wait_for_mongod(config)
    except StageFailed as err:
        emit("configure_mongod", STATUS_FAILED, str(err))
        sys.exit(1)
    emit("configure_mongod", STATUS_OK)

    emit("initialize_replica_set", STATUS_STARTED)
    try:
        initiate_replica_set(config)
    except StageFailed as err:
        emit("initialize_replica_set", STATUS_FAILED, str(err))
        sys.exit(1)
    emit("initialize_replica_set", STATUS_OK)


if __name__ == "__main__":
    main()
